[build]
builder = "Railpack"
buildCommand = "pnpm install && pnpm --filter @workspace/api-server run build"

[deploy]
startCommand = "pnpm --filter @workspace/db run push && pnpm --filter @workspace/scripts run seed:duas && pnpm --filter @workspace/scripts run seed:tasbih && node --enable-source-maps ./artifacts/api-server/dist/index.mjs"

healthcheckPath = "/api/healthz"
restartPolicyType = "on_failure"

[variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
