import { db, tasbihPresetsTable } from "@workspace/db";
import { eq, count } from "drizzle-orm";

const PRESETS = [
  // ═══ MORNING (فجر / صباح) — 15 items ═══
  { phraseAr: "سبحان الله", transliteration: "SubhanAllah", translationAr: "تنزيه الله", meaning: "Glory be to Allah", recommendedCount: 33, category: "تسبيح", timeOfDay: "morning", spiritualNote: "من أحب الكلام إلى الله", orderIndex: 1, isFeatured: true },
  { phraseAr: "الحمد لله", transliteration: "Alhamdulillah", translationAr: "شكر الله", meaning: "Praise be to Allah", recommendedCount: 33, category: "تسبيح", timeOfDay: "morning", spiritualNote: "تملأ الميزان", orderIndex: 2, isFeatured: true },
  { phraseAr: "الله أكبر", transliteration: "Allahu Akbar", translationAr: "تعظيم الله", meaning: "Allah is the Greatest", recommendedCount: 34, category: "تسبيح", timeOfDay: "morning", spiritualNote: "كلمة عظيمة عند الله", orderIndex: 3, isFeatured: true },
  { phraseAr: "سبحان الله وبحمده", transliteration: "SubhanAllahi wa bihamdihi", translationAr: "التسبيح مع الحمد", meaning: "Glory be to Allah and His praise", recommendedCount: 100, category: "تسبيح", timeOfDay: "morning", spiritualNote: "من قالها مائة مرة حين يصبح وحين يمسي لم يأت أحد بأفضل مما جاء به", orderIndex: 4, isFeatured: true },
  { phraseAr: "لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير", transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa ala kulli shay'in qadir", translationAr: "كلمة التوحيد", meaning: "There is no god but Allah alone", recommendedCount: 10, category: "تهليل", timeOfDay: "morning", spiritualNote: "من قالها عشر مرات كان كمن أعتق أربعة أنفس من ولد إسماعيل", orderIndex: 5, isFeatured: true },
  { phraseAr: "اللهم إني أصبحت أشهدك وأشهد حملة عرشك وملائكتك وجميع خلقك أنك أنت الله لا إله إلا أنت", transliteration: "Allahumma inni asbahtu ush-hiduka wa ush-hidu hamalata arshika wa mala'ikataka wa jami'a khalqika annaka antallahu la ilaha illa ant", translationAr: "دعاء الصباح", meaning: "O Allah, I have reached the morning and call You to witness", recommendedCount: 4, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "من قالها أربع مرات حين يصبح أعتقه الله من النار", orderIndex: 6, isFeatured: false },
  { phraseAr: "اللهم ما أصبح بي من نعمة أو بأحد من خلقك فمنك وحدك لا شريك لك، فلك الحمد ولك الشكر", transliteration: "Allahumma ma asbaha bi min ni'matin aw bi ahadin min khalqika faminka wahdaka la sharika lak", translationAr: "شكر النعمة", meaning: "O Allah, whatever blessing I have reached the morning with is from You alone", recommendedCount: 1, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "من قالها حين يصبح فقد أدى شكر يومه", orderIndex: 7, isFeatured: false },
  { phraseAr: "اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري، لا إله إلا أنت", transliteration: "Allahumma afini fi badani, Allahumma afini fi sam'i, Allahumma afini fi basari, la ilaha illa ant", translationAr: "دعاء العافية", meaning: "O Allah, grant me health in my body, hearing, and sight", recommendedCount: 3, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "كان النبي ﷺ يقولها ثلاثاً حين يصبح وحين يمسي", orderIndex: 8, isFeatured: false },
  { phraseAr: "حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم", transliteration: "Hasbiyallahu la ilaha illa Huwa alayhi tawakkaltu wa Huwa Rabbul-arshil-azeem", translationAr: "التوكل على الله", meaning: "Allah is sufficient for me", recommendedCount: 7, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "من قالها سبع مرات كفاه الله ما أهمه", orderIndex: 9, isFeatured: false },
  { phraseAr: "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم", transliteration: "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i", translationAr: "التحصين باسم الله", meaning: "In the name of Allah, with whose name nothing is harmed", recommendedCount: 3, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "من قالها ثلاثاً لم تصبه فجأة بلاء", orderIndex: 10, isFeatured: false },
  { phraseAr: "رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ نبياً", transliteration: "Raditu billahi Rabba, wa bil-Islami dina, wa bi-Muhammadin ﷺ nabiyya", translationAr: "الرضا بالله", meaning: "I am pleased with Allah as Lord, Islam as religion", recommendedCount: 3, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "كان حقاً على الله أن يرضيه يوم القيامة", orderIndex: 11, isFeatured: false },
  { phraseAr: "يا حي يا قيوم برحمتك أستغيث أصلح لي شأني كله ولا تكلني إلى نفسي طرفة عين", transliteration: "Ya Hayyu Ya Qayyum, bi-rahmatika astaghith, aslih li sha'ni kullahu", translationAr: "الاستغاثة", meaning: "O Ever-Living, O Sustainer, by Your mercy I seek help", recommendedCount: 1, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "دعاء عظيم للإصلاح والتوفيق", orderIndex: 12, isFeatured: false },
  { phraseAr: "أصبحنا وأصبح الملك لله والحمد لله، لا إله إلا الله وحده لا شريك له", transliteration: "Asbahna wa asbahal-mulku lillahi wal-hamdu lillah, la ilaha illallahu wahdahu la sharika lah", translationAr: "ذكر الصباح", meaning: "We have reached the morning and unto Allah belongs all sovereignty", recommendedCount: 1, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "من أذكار الصباح الجامعة", orderIndex: 13, isFeatured: false },
  { phraseAr: "اللهم إني أسألك العفو والعافية في الدنيا والآخرة", transliteration: "Allahumma inni as'alukal-afwa wal-afiyata fid-dunya wal-akhirah", translationAr: "سؤال العفو والعافية", meaning: "O Allah, I ask You for pardon and well-being in this life and the next", recommendedCount: 1, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "كان النبي ﷺ يكثر من هذا الدعاء", orderIndex: 14, isFeatured: false },
  { phraseAr: "اللهم إني أسألك الهدى والتقى والعفاف والغنى", transliteration: "Allahumma inni as'alukal-huda wat-tuqa wal-afafa wal-ghina", translationAr: "سؤال الخير", meaning: "O Allah, I ask You for guidance, piety, chastity, and contentment", recommendedCount: 1, category: "دعاء الصباح", timeOfDay: "morning", spiritualNote: "من أجمع أدعية النبي ﷺ", orderIndex: 15, isFeatured: false },

  // ═══ AFTERNOON (ظهر / عصر) — 15 items ═══
  { phraseAr: "أستغفر الله", transliteration: "Astaghfirullah", translationAr: "طلب المغفرة", meaning: "I seek forgiveness from Allah", recommendedCount: 100, category: "استغفار", timeOfDay: "afternoon", spiritualNote: "من لزم الاستغفار جعل الله له من كل ضيق مخرجاً", orderIndex: 16, isFeatured: true },
  { phraseAr: "لا حول ولا قوة إلا بالله", transliteration: "La hawla wa la quwwata illa billah", translationAr: "كنز من كنوز الجنة", meaning: "No power nor strength except with Allah", recommendedCount: 100, category: "حوقلة", timeOfDay: "afternoon", spiritualNote: "كنز من كنوز الجنة", orderIndex: 17, isFeatured: true },
  { phraseAr: "سبحان الله العظيم وبحمده", transliteration: "SubhanAllahi al-Azeem wa bihamdihi", translationAr: "تنزيه الله العظيم", meaning: "Glory be to Allah the Magnificent and His praise", recommendedCount: 100, category: "تسبيح", timeOfDay: "afternoon", spiritualNote: "كلمتان حبيبتان إلى الرحمن، خفيفتان على اللسان، ثقيلتان في الميزان", orderIndex: 18, isFeatured: true },
  { phraseAr: "لا إله إلا الله", transliteration: "La ilaha illallah", translationAr: "كلمة التوحيد", meaning: "There is no god but Allah", recommendedCount: 100, category: "تهليل", timeOfDay: "afternoon", spiritualNote: "أفضل ما قلت أنا والنبيون من قبلي", orderIndex: 19, isFeatured: true },
  { phraseAr: "سبحان الله والحمد لله ولا إله إلا الله والله أكبر", transliteration: "SubhanAllahi wal-hamdu lillahi wa la ilaha illallahu wallahu Akbar", translationAr: "الباقينات", meaning: "The enduring good deeds", recommendedCount: 100, category: "تسبيح", timeOfDay: "afternoon", spiritualNote: "الباقيات الصالحات، أحب إلى النبي ﷺ مما طلعت عليه الشمس", orderIndex: 20, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من العجز والكسل والجبن والبخل والهرم وعذاب القبر", transliteration: "Allahumma inni a'udhu bika minal-ajzi wal-kasali wal-jubni wal-bukhri wal-harami wa adhabil-qabr", translationAr: "الاستعاذة من الشرور", meaning: "O Allah, I seek refuge from incapacity, laziness, cowardice", recommendedCount: 1, category: "دعاء", timeOfDay: "afternoon", spiritualNote: "دعاء شامل من ست آفات", orderIndex: 21, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من علم لا ينفع، ومن قلب لا يخشع، ومن نفس لا تشبع، ومن دعوة لا يستجاب لها", transliteration: "Allahumma inni a'udhu bika min ilmin la yanfa', wa min qalbin la yakhsha'", translationAr: "الاستعاذة", meaning: "O Allah, I seek refuge from knowledge that does not benefit", recommendedCount: 1, category: "دعاء", timeOfDay: "afternoon", spiritualNote: "من أجمع أدعية الاستعاذة", orderIndex: 22, isFeatured: false },
  { phraseAr: "اللهم اغفر لي ذنبي كله، دقه وجله، وأوله وآخره، وعلانيته وسره", transliteration: "Allahumma-ghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirahu", translationAr: "طلب المغفرة الشاملة", meaning: "O Allah, forgive me all my sins, small and great", recommendedCount: 1, category: "استغفار", timeOfDay: "afternoon", spiritualNote: "من أجمع أدعية الاستغفار", orderIndex: 23, isFeatured: false },
  { phraseAr: "اللهم صل وسلم على نبينا محمد", transliteration: "Allahumma salli wa sallim ala nabiyyina Muhammad", translationAr: "الصلاة على النبي", meaning: "O Allah, send blessings and peace upon our Prophet", recommendedCount: 100, category: "صلاة على النبي", timeOfDay: "afternoon", spiritualNote: "من صلى عليّ صلاة صلى الله عليه بها عشراً", orderIndex: 24, isFeatured: false },
  { phraseAr: "اللهم إني ظلمت نفسي ظلماً كثيراً ولا يغفر الذنوب إلا أنت، فاغفر لي مغفرة من عندك وارحمني", transliteration: "Allahumma inni zalamtu nafsi zulman kathiran wa la yaghfirudh-dhunuba illa ant, faghfir li maghfiratan min indika warhamni", translationAr: "سيد الاستغفار", meaning: "O Allah, I have wronged myself greatly and none forgives sins except You", recommendedCount: 1, category: "استغفار", timeOfDay: "afternoon", spiritualNote: "سيد الاستغفار", orderIndex: 25, isFeatured: false },
  { phraseAr: "رب اغفر لي وارحمني واهدني وارزقني وعافني", transliteration: "Rabbighfir li warhamni wahdini warzuqni wa afini", translationAr: "دعاء شامل", meaning: "My Lord, forgive me, have mercy on me, guide me, provide for me, and grant me health", recommendedCount: 1, category: "دعاء", timeOfDay: "afternoon", spiritualNote: "جمع النبي ﷺ بين هذه الخمس", orderIndex: 26, isFeatured: false },
  { phraseAr: "اللهم إني أسألك من فضلك ورحمتك فإنه لا يملكها إلا أنت", transliteration: "Allahumma inni as'aluka min fadlika wa rahmatika fa-innahu la yamlikuha illa ant", translationAr: "سؤال الفضل والرحمة", meaning: "O Allah, I ask You from Your bounty and mercy", recommendedCount: 1, category: "دعاء", timeOfDay: "afternoon", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 27, isFeatured: false },
  { phraseAr: "يا ذا الجلال والإكرام", transliteration: "Ya Dhal-Jalali wal-Ikram", translationAr: "يا رب العظمة والكرم", meaning: "O Possessor of Majesty and Honor", recommendedCount: 100, category: "دعاء", timeOfDay: "afternoon", spiritualNote: "كان النبي ﷺ يكثر من قولها", orderIndex: 28, isFeatured: false },
  { phraseAr: "لا إله إلا الله العظيم الحليم، لا إله إلا الله رب العرش العظيم", transliteration: "La ilaha illallahu al-Azeemul-Haleem, la ilaha illallahu Rabbul-arshil-azeem", translationAr: "كلمة التوحيد", meaning: "There is no god but Allah the Magnificent, the Forbearing", recommendedCount: 7, category: "تهليل", timeOfDay: "afternoon", spiritualNote: "من أذكار النبي ﷺ", orderIndex: 29, isFeatured: false },
  { phraseAr: "اللهم إني أسألك حبك وحب من يحبك وحب عمل يقربني إلى حبك", transliteration: "Allahumma inni as'aluka hubbaka wa hubba man yuhibbuka wa hubba amalin yuqarribuni ila hubbik", translationAr: "سؤال حب الله", meaning: "O Allah, I ask You for Your love and the love of those who love You", recommendedCount: 1, category: "دعاء", timeOfDay: "afternoon", spiritualNote: "من أجمع الأدعية", orderIndex: 30, isFeatured: false },

  // ═══ EVENING (مغرب / عشاء) — 15 items ═══
  { phraseAr: "اللهم صل على محمد وعلى آل محمد كما صليت على إبراهيم إنك حميد مجيد", transliteration: "Allahumma salli ala Muhammadin wa ala ali Muhammadin kama sallayta ala Ibrahima", translationAr: "الصلاة الإبراهيمية", meaning: "O Allah, send blessings upon Muhammad and his family", recommendedCount: 10, category: "صلاة على النبي", timeOfDay: "evening", spiritualNote: "الصلاة الإبراهيمية في التشهد", orderIndex: 31, isFeatured: true },
  { phraseAr: "أعوذ بكلمات الله التامات من شر ما خلق", transliteration: "A'udhu bi-kalimatillahit-tammati min sharri ma khalaq", translationAr: "الاستعاذة بكلمات الله", meaning: "I seek refuge in the perfect words of Allah", recommendedCount: 3, category: "استعاذة", timeOfDay: "evening", spiritualNote: "من قالها لم يضره شيء حتى يصبح", orderIndex: 32, isFeatured: false },
  { phraseAr: "اللهم إني أمسيت أشهدك وأشهد حملة عرشك وملائكتك وجميع خلقك أنك أنت الله لا إله إلا أنت", transliteration: "Allahumma inni amsaytu ush-hiduka wa ush-hidu hamalata arshika wa mala'ikataka", translationAr: "دعاء المساء", meaning: "O Allah, I have reached the evening and call You to witness", recommendedCount: 4, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من قالها أربع مرات حين يمسي أعتقه الله من النار", orderIndex: 33, isFeatured: false },
  { phraseAr: "اللهم ما أمسى بي من نعمة أو بأحد من خلقك فمنك وحدك لا شريك لك، فلك الحمد ولك الشكر", transliteration: "Allahumma ma amsa bi min ni'matin aw bi ahadin min khalqika faminka wahdaka la sharika lak", translationAr: "شكر نعمة المساء", meaning: "O Allah, whatever blessing I have reached the evening with is from You alone", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من قالها حين يمسي فقد أدى شكر ليلته", orderIndex: 34, isFeatured: false },
  { phraseAr: "اللهم إني أسألك الجنة وما قرب إليها من قول أو عمل، وأعوذ بك من النار وما قرب إليها", transliteration: "Allahumma inni as'alukal-Jannata wa ma qarraba ilayha min qawlin aw amal, wa a'udhu bika minan-Nar", translationAr: "سؤال الجنة والاستعاذة من النار", meaning: "O Allah, I ask You for Paradise and seek refuge from the Fire", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أجمع الأدعية", orderIndex: 35, isFeatured: false },
  { phraseAr: "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار", transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina adhab an-Nar", translationAr: "دعاء شامل", meaning: "Our Lord, give us good in this world and good in the Hereafter", recommendedCount: 33, category: "دعاء", timeOfDay: "evening", spiritualNote: "كان النبي ﷺ يكثر من هذا الدعاء", orderIndex: 36, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من الهم والحزن، والعجز والكسل، والبخل والجبن، وضلع الدين وغلبة الرجال", transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-ajzi wal-kasal, wal-bukhri wal-jubn", translationAr: "الاستعاذة من الهموم", meaning: "O Allah, I seek refuge from anxiety and sorrow, weakness and laziness", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أعظم أدعية الاستعاذة", orderIndex: 37, isFeatured: false },
  { phraseAr: "أمسينا وأمسى الملك لله والحمد لله، لا إله إلا الله وحده لا شريك له", transliteration: "Amsayna wa amsal-mulku lillahi wal-hamdu lillah, la ilaha illallahu wahdahu la sharika lah", translationAr: "ذكر المساء", meaning: "We have reached the evening and unto Allah belongs all sovereignty", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أذكار المساء الجامعة", orderIndex: 38, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من شر ما عملت ومن شر ما لم أعمل", transliteration: "Allahumma inni a'udhu bika min sharri ma amiltu wa min sharri ma lam a'mal", translationAr: "الاستعاذة من الشر", meaning: "O Allah, I seek refuge from the evil of what I have done and what I have not done", recommendedCount: 1, category: "استعاذة", timeOfDay: "evening", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 39, isFeatured: false },
  { phraseAr: "اللهم عالم الغيب والشهادة فاطر السماوات والأرض، رب كل شيء ومليكه، أشهد أن لا إله إلا أنت، أعوذ بك من شر نفسي وشر الشيطان وشركه", transliteration: "Allahumma alimal-ghaybi wash-shahadah, fatiras-samawati wal-ard, Rabba kulli shay'in wa malikah", translationAr: "دعاء شامل", meaning: "O Allah, Knower of the unseen and seen, Creator of the heavens and earth", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أجمع أدعية النبي ﷺ", orderIndex: 40, isFeatured: false },
  { phraseAr: "اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك المصير", transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal-masir", translationAr: "دعاء المساء", meaning: "O Allah, by Your will we reach the evening and by Your will we live and die", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "كان النبي ﷺ يقولها حين يمسي", orderIndex: 41, isFeatured: false },
  { phraseAr: "اللهم إني أسألك خير هذه الليلة فتحها ونصرها ونورها وبركتها وهداها", transliteration: "Allahumma inni as'aluka khayra hadhihil-laylah fathaha wa nasraha wa nuraha wa barakataha", translationAr: "سؤال خير الليلة", meaning: "O Allah, I ask You for the good of this night", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 42, isFeatured: false },
  { phraseAr: "اللهم اجعل في قلبي نوراً وفي بصري نوراً وفي سمعي نوراً وعن يميني نوراً وعن يساري نوراً", transliteration: "Allahumma-ij'al fi qalbi nuran wa fi basari nuran wa fi sam'i nuran wa an yamini nuran wa an yasari nuran", translationAr: "سؤال النور", meaning: "O Allah, place light in my heart, sight, hearing, right and left", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أدعية النبي ﷺ الجامعة", orderIndex: 43, isFeatured: false },
  { phraseAr: "اللهم إني أسألك من خير ما سألك منه نبيك محمد ﷺ وأعوذ بك من شر ما استعاذ منه نبيك محمد ﷺ", transliteration: "Allahumma inni as'aluka min khayri ma sa'alaka minhu nabiyyuka Muhammadun ﷺ wa a'udhu bika min sharri mast'aadha minhu nabiyyuka Muhammad ﷺ", translationAr: "سؤال الخير والاستعاذة من الشر", meaning: "O Allah, I ask You for the good that Your Prophet asked for", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "من أجمع الأدعية", orderIndex: 44, isFeatured: false },
  { phraseAr: "بسم الله توكلت على الله ولا حول ولا قوة إلا بالله", transliteration: "Bismillah tawakkaltu alallahi wa la hawla wa la quwwata illa billah", translationAr: "التوكل على الله", meaning: "In the name of Allah, I put my trust in Allah", recommendedCount: 1, category: "دعاء المساء", timeOfDay: "evening", spiritualNote: "يقال لها كفاية وهادية", orderIndex: 45, isFeatured: false },

  // ═══ NIGHT (قبل النوم) — 15 items ═══
  { phraseAr: "اللهم إني أسألك الجنة", transliteration: "Allahumma inni as'aluka al-Jannah", translationAr: "سؤال الجنة", meaning: "O Allah, I ask You for Paradise", recommendedCount: 33, category: "دعاء", timeOfDay: "night", spiritualNote: "من سأل الله الجنة ثلاثاً قالت الجنة: اللهم أدخله الجنة", orderIndex: 46, isFeatured: true },
  { phraseAr: "أعوذ بالله من النار", transliteration: "A'udhu billahi min an-Nar", translationAr: "الاستعاذة من النار", meaning: "I seek refuge in Allah from the Fire", recommendedCount: 33, category: "دعاء", timeOfDay: "night", spiritualNote: "من تعوذ بالله من النار ثلاثاً قالت النار: اللهم أجره من النار", orderIndex: 47, isFeatured: true },
  { phraseAr: "رب اغفر لي وتب علي إنك أنت التواب الغفور", transliteration: "Rabbighfir li wa tub alayya innaka antat-Tawwab al-Ghafoor", translationAr: "طلب المغفرة والتوبة", meaning: "My Lord, forgive me and accept my repentance", recommendedCount: 100, category: "استغفار", timeOfDay: "night", spiritualNote: "سيد الاستغفار", orderIndex: 48, isFeatured: true },
  { phraseAr: "اللهم باسمك أموت وأحيا", transliteration: "Allahumma bismika amutu wa ahya", translationAr: "دعاء النوم", meaning: "O Allah, in Your name I die and I live", recommendedCount: 1, category: "دعاء النوم", timeOfDay: "night", spiritualNote: "كان النبي ﷺ يقولها إذا أوى إلى فراشه", orderIndex: 49, isFeatured: false },
  { phraseAr: "سبحان الله (33) الحمد لله (33) الله أكبر (34)", transliteration: "SubhanAllah (33) Alhamdulillah (33) Allahu Akbar (34)", translationAr: "تسبيح فاطمة", meaning: "The Tasbih of Fatimah", recommendedCount: 100, category: "تسبيح", timeOfDay: "night", spiritualNote: "وصية النبي ﷺ لفاطمة وعلي رضي الله عنهما قبل النوم", orderIndex: 50, isFeatured: false },
  { phraseAr: "اللهم قني عذابك يوم تبعث عبادك", transliteration: "Allahumma qini adhabaka yawma tab'athu ibadak", translationAr: "دعاء قبل النوم", meaning: "O Allah, protect me from Your punishment on the Day of Resurrection", recommendedCount: 3, category: "دعاء النوم", timeOfDay: "night", spiritualNote: "كان النبي ﷺ يقولها ثلاثاً عند النوم", orderIndex: 51, isFeatured: false },
  { phraseAr: "اللهم رب السماوات السبع ورب العرش العظيم، ربنا ورب كل شيء، أعوذ بك من شر كل شيء أنت آخذ بناصيته", transliteration: "Allahumma Rabbas-samawatis-sab'i wa Rabbal-arshil-azeem, Rabbana wa Rabba kulli shay'in, a'udhu bika min sharri kulli shay'in anta akhidhun binasiyatih", translationAr: "دعاء شامل", meaning: "O Allah, Lord of the seven heavens and the Mighty Throne", recommendedCount: 1, category: "دعاء النوم", timeOfDay: "night", spiritualNote: "من أجمع أدعية النبي ﷺ", orderIndex: 52, isFeatured: false },
  { phraseAr: "لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير", transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa ala kulli shay'in qadir", translationAr: "كلمة التوحيد", meaning: "There is no god but Allah alone", recommendedCount: 100, category: "تهليل", timeOfDay: "night", spiritualNote: "كان النبي ﷺ يقولها قبل النوم", orderIndex: 53, isFeatured: false },
  { phraseAr: "اللهم إني أسلمت نفسي إليك، ووجهت وجهي إليك، وفوضت أمري إليك، وألجأت ظهري إليك، رغبة ورهبة إليك", transliteration: "Allahumma inni aslamtu nafsi ilayk, wa wajjahtu wajhi ilayk, wa fawwadtu amri ilayk, wa alja'tu zahri ilayk, raghbatan wa rahbatan ilayk", translationAr: "دعاء النوم الشامل", meaning: "O Allah, I submit myself to You, I turn my face to You", recommendedCount: 1, category: "دعاء النوم", timeOfDay: "night", spiritualNote: "من قالها فمات من ليلته فقد مات على الفطرة", orderIndex: 54, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من سوء القضاء ومن درك الشقاء ومن شماتة الأعداء ومن جهد البلاء", transliteration: "Allahumma inni a'udhu bika min su'il-qada' wa min darkish-shaqa' wa min shamatatil-a'da' wa min jahdil-bala'", translationAr: "الاستعاذة", meaning: "O Allah, I seek refuge from evil decree, misery, enemies' gloating, and severe trial", recommendedCount: 1, category: "دعاء النوم", timeOfDay: "night", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 55, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من شر ما خلقت", transliteration: "Allahumma inni a'udhu bika min sharri ma khalaqt", translationAr: "الاستعاذة من الشر", meaning: "O Allah, I seek refuge from the evil of what You have created", recommendedCount: 1, category: "استعاذة", timeOfDay: "night", spiritualNote: "كان النبي ﷺ يقولها قبل النوم", orderIndex: 56, isFeatured: false },
  { phraseAr: "اللهم اغفر لي ما قدمت وما أخرت، وما أسررت وما أعلنت، وما أسرفت وما أنت أعلم به مني", transliteration: "Allahumma-ghfir li ma qaddamtu wa ma akhkhartu, wa ma asrartu wa ma a'lantu, wa ma asraftu wa ma anta a'lamu bihi minni", translationAr: "طلب المغفرة الشاملة", meaning: "O Allah, forgive me what I have sent forth and what I have deferred", recommendedCount: 1, category: "استغفار", timeOfDay: "night", spiritualNote: "من أجمع أدعية الاستغفار", orderIndex: 57, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بوجهك الكريم وكلماتك التامة من سخطك وعقابك، ومن شر عباده، ومن همزات الشياطين", transliteration: "Allahumma inni a'udhu bi-wajhikal-karim wa kalimatikat-tammah min sakhatika wa iqabik, wa min sharri ibadik, wa min hamazatish-shayatin", translationAr: "الاستعاذة", meaning: "O Allah, I seek refuge by Your noble Face from Your anger and punishment", recommendedCount: 1, category: "استعاذة", timeOfDay: "night", spiritualNote: "من أجمع أدعية الاستعاذة", orderIndex: 58, isFeatured: false },
  { phraseAr: "سبحان الله وبحمده عدد خلقه ورضا نفسه وزنة عرشه ومداد كلماته", transliteration: "SubhanAllahi wa bihamdihi adada khalqihi wa rida nafsihi wa zinata arshihi wa midada kalimatihi", translationAr: "التسبيح العظيم", meaning: "Glory be to Allah and His praise, by the multitude of His creation", recommendedCount: 3, category: "تسبيح", timeOfDay: "night", spiritualNote: "تعدل ثلاث تسبيحات", orderIndex: 59, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من الفقر والقلة والذلة وأعوذ بك من أن أظلم أو أظلم", transliteration: "Allahumma inni a'udhu bika minal-faqri wal-qillati wadh-dhillah, wa a'udhu bika min an azlima aw uzlam", translationAr: "الاستعاذة من الفقر", meaning: "O Allah, I seek refuge from poverty, lack, humiliation, and from wronging or being wronged", recommendedCount: 1, category: "دعاء النوم", timeOfDay: "night", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 60, isFeatured: false },

  // ═══ GENERAL (كل وقت - Hajj specific) — 40 items ═══
  { phraseAr: "لبيك اللهم لبيك، لبيك لا شريك لك لبيك، إن الحمد والنعمة لك والملك، لا شريك لك", transliteration: "Labbayk Allahumma labbayk, labbayk la sharika laka labbayk, innal-hamda wan-ni'mata laka wal-mulk", translationAr: "التلبية", meaning: "Here I am O Allah, here I am", recommendedCount: 100, category: "تلبية", timeOfDay: "general", spiritualNote: "التلبية شعار الحجيج", orderIndex: 61, isFeatured: true },
  { phraseAr: "اللهم صل على محمد", transliteration: "Allahumma salli ala Muhammad", translationAr: "الصلاة على النبي", meaning: "O Allah, send blessings upon Muhammad", recommendedCount: 100, category: "صلاة على النبي", timeOfDay: "general", spiritualNote: "من صلى عليّ صلاة صلى الله عليه بها عشراً", orderIndex: 62, isFeatured: false },
  { phraseAr: "أستغفر الله العظيم وأتوب إليه", transliteration: "Astaghfirullaha al-Azeem wa atubu ilayh", translationAr: "الاستغفار", meaning: "I seek forgiveness from Allah the Magnificent and repent to Him", recommendedCount: 100, category: "استغفار", timeOfDay: "general", spiritualNote: "كان النبي ﷺ يستغفر في المجلس الواحد أكثر من سبعين مرة", orderIndex: 63, isFeatured: false },
  { phraseAr: "لا إله إلا أنت سبحانك إني كنت من الظالمين", transliteration: "La ilaha illa anta subhanaka inni kuntu minaz-zalimin", translationAr: "دعاء ذي النون", meaning: "There is no god but You, glory be to You, I was among the wrongdoers", recommendedCount: 40, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء يونس في بطن الحوت - ما دعا بها مسلم إلا استجاب الله له", orderIndex: 64, isFeatured: false },
  { phraseAr: "رب اشرح لي صدري ويسر لي أمري واحلل عقدة من لساني يفقهوا قولي", transliteration: "Rabbishrah li sadri, wa yassir li amri, wahlul uqdatan min lisani, yafqahu qawli", translationAr: "دعاء موسى", meaning: "My Lord, expand my chest, ease my task", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء موسى عليه السلام", orderIndex: 65, isFeatured: false },
  { phraseAr: "ربنا لا تؤاخذنا إن نسينا أو أخطأنا، ربنا ولا تحمل علينا إصراً", transliteration: "Rabbana la tu'akhidhna in nasina aw akhta'na, Rabbana wa la tahmil alayna isran", translationAr: "دعاء شامل", meaning: "Our Lord, do not impose blame upon us if we forget or err", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من آيات سورة البقرة", orderIndex: 66, isFeatured: false },
  { phraseAr: "ربنا هب لنا من أزواجنا وذرياتنا قرة أعين واجعلنا للمتقين إماماً", transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama", translationAr: "دعاء الأسرة", meaning: "Our Lord, grant us from our spouses and offspring comfort to our eyes", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من دعاء الصالحين", orderIndex: 67, isFeatured: false },
  { phraseAr: "ربنا اغفر لنا ولإخواننا الذين سبقونا بالإيمان ولا تجعل في قلوبنا غلاً للذين آمنوا", transliteration: "Rabbanaghfir lana wa li-ikhwaninal-ladhina sabaquna bil-imani wa la taj'al fi qulubina ghillan", translationAr: "دعاء للمؤمنين", meaning: "Our Lord, forgive us and our brothers who preceded us in faith", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة الحشر", orderIndex: 68, isFeatured: false },
  { phraseAr: "سبحان الله وبحمده سبحان الله العظيم", transliteration: "SubhanAllahi wa bihamdihi, SubhanAllahi al-Azeem", translationAr: "التسبيح المزدوج", meaning: "Glory be to Allah and His praise, Glory be to Allah the Magnificent", recommendedCount: 100, category: "تسبيح", timeOfDay: "general", spiritualNote: "كلمتان خفيفتان على اللسان ثقيلتان في الميزان", orderIndex: 69, isFeatured: false },
  { phraseAr: "الله أكبر كبيراً والحمد لله كثيراً وسبحان الله بكرة وأصيلاً", transliteration: "Allahu Akbar kabira, wal-hamdu lillahi kathira, wa SubhanAllahi bukratan wa asila", translationAr: "التعظيم والحمد", meaning: "Allah is the Greatest, greatly, and praise be to Allah abundantly", recommendedCount: 33, category: "تسبيح", timeOfDay: "general", spiritualNote: "كان النبي ﷺ يقولها كثيراً", orderIndex: 70, isFeatured: false },
  { phraseAr: "اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت", transliteration: "Allahumma anta Rabbi la ilaha illa ant, khalaqtani wa ana abduk, wa ana ala ahdika wa wa'dika mastata't", translationAr: "سيد الاستغفار", meaning: "O Allah, You are my Lord, there is no god but You", recommendedCount: 1, category: "استغفار", timeOfDay: "general", spiritualNote: "سيد الاستغفار - من قالها موقناً بها فمات دخل الجنة", orderIndex: 71, isFeatured: false },
  { phraseAr: "ربنا تقبل منا إنك أنت السميع العليم وتب علينا إنك أنت التواب الرحيم", transliteration: "Rabbana taqabbal minna innaka antas-Sami'ul-Aleem wa tub alayna innaka antat-Tawwabur-Rahim", translationAr: "دعاء القبول", meaning: "Our Lord, accept from us, indeed You are the All-Hearing", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء إبراهيم وإسماعيل عند بناء الكعبة", orderIndex: 72, isFeatured: false },
  { phraseAr: "ربنا ظلمنا أنفسنا وإن لم تغفر لنا وترحمنا لنكونن من الخاسرين", transliteration: "Rabbana zalamna anfusina wa il-lam taghfir lana wa tarhamna lanakunanna minal-khasirin", translationAr: "دعاء آدم", meaning: "Our Lord, we have wronged ourselves", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء آدم وحواء عليهما السلام", orderIndex: 73, isFeatured: false },
  { phraseAr: "ربنا أفرغ علينا صبراً وثبت أقدامنا وانصرنا على القوم الكافرين", transliteration: "Rabbana afrigh alayna sabran wa thabbit aqdamana wansurna alal-qawmil-kafirin", translationAr: "دعاء الثبات", meaning: "Our Lord, pour upon us patience, make our feet firm, and grant us victory", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء طالوت وجنوده", orderIndex: 74, isFeatured: false },
  { phraseAr: "ربنا لا تزغ قلوبنا بعد إذ هديتنا وهب لنا من لدنك رحمة إنك أنت الوهاب", transliteration: "Rabbana la tuzigh qulubana ba'da idh hadaytana wa hab lana min ladunka rahmah innaka antal-Wahhab", translationAr: "دعاء الثبات على الهدى", meaning: "Our Lord, let not our hearts deviate after You have guided us", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة آل عمران", orderIndex: 75, isFeatured: false },
  { phraseAr: "ربنا إنك تعلم ما نخفي وما نعلن وما يخفى على الله من شيء في الأرض ولا في السماء", transliteration: "Rabbana innaka ta'lamu ma nukhfi wa ma nu'lin wa ma yakhfa alallahi min shay'in fil-ardi wa la fis-sama'", translationAr: "دعاء", meaning: "Our Lord, indeed You know what we conceal and what we declare", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة إبراهيم", orderIndex: 76, isFeatured: false },
  { phraseAr: "رب اجعلني مقيم الصلاة ومن ذريتي ربنا وتقبل دعاء", transliteration: "Rabbij'alni muqimas-salati wa min dhurriyyati Rabbana wa taqabbal du'a", translationAr: "دعاء الصلاة", meaning: "My Lord, make me an establisher of prayer, and from my descendants", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء إبراهيم عليه السلام", orderIndex: 77, isFeatured: false },
  { phraseAr: "ربنا اغفر لي ولوالدي وللمؤمنين يوم يقوم الحساب", transliteration: "Rabbanaghfir li wa liwalidayya wa lilmu'minina yawma yaqumul-hisab", translationAr: "دعاء المغفرة", meaning: "Our Lord, forgive me and my parents and the believers on the Day of Account", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء إبراهيم عليه السلام", orderIndex: 78, isFeatured: false },
  { phraseAr: "ربنا آتنا من لدنك رحمة وهيئ لنا من أمرنا رشداً", transliteration: "Rabbana atina min ladunka rahmah wa hayyi' lana min amrina rashada", translationAr: "دعاء التوفيق", meaning: "Our Lord, grant us mercy from Yourself and prepare for us right guidance", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء أهل الكهف", orderIndex: 79, isFeatured: false },
  { phraseAr: "رب إني لما أنزلت إلي من خير فقير", transliteration: "Rabbi inni lima anzalta ilayya min khairin faqir", translationAr: "دعاء الحاجة", meaning: "My Lord, indeed I am in need of whatever good You send down to me", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء موسى عليه السلام", orderIndex: 80, isFeatured: false },
  { phraseAr: "رب أدخلني مدخل صدق وأخرجني مخرج صدق واجعل لي من لدنك سلطاناً نصيراً", transliteration: "Rabbi adkhilni mudkhala sidqin wa akhrijni mukhraja sidqin waj'al li min ladunka sultanan nasira", translationAr: "دعاء التوفيق", meaning: "My Lord, cause me to enter a sound entrance and exit", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة الإسراء", orderIndex: 81, isFeatured: false },
  { phraseAr: "ربنا عليك توكلنا وإليك أنبنا وإليك المصير", transliteration: "Rabbana alayka tawakkalna wa ilayka anabna wa ilaykal-masir", translationAr: "دعاء التوكل", meaning: "Our Lord, upon You we have relied, and to You we have returned", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة الممتحنة", orderIndex: 82, isFeatured: false },
  { phraseAr: "ربنا لا تجعلنا فتنة للذين كفروا واغفر لنا ربنا إنك أنت العزيز الحكيم", transliteration: "Rabbana la taj'alna fitnatal-lilladhina kafaru waghfir lana Rabbana innaka antal-Azizul-Hakim", translationAr: "دعاء", meaning: "Our Lord, do not make us a trial for those who disbelieve", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة الممتحنة", orderIndex: 83, isFeatured: false },
  { phraseAr: "رب أوزعني أن أشكر نعمتك التي أنعمت علي وعلى والدي وأن أعمل صالحاً ترضاه", transliteration: "Rabbi awzi'ni an ashkura ni'matakallati an'amta alayya wa ala walidayya wa an a'mala salihan tardah", translationAr: "دعاء الشكر", meaning: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء سليمان عليه السلام", orderIndex: 84, isFeatured: false },
  { phraseAr: "رب إني أعوذ بك أن أسألك ما ليس لي به علم وإلا تغفر لي وترحمني أكن من الخاسرين", transliteration: "Rabbi inni a'udhu bika an as'alaka ma laysa li bihi ilm, wa illa taghfir li wa tarhamni akun minal-khasirin", translationAr: "دعاء الاستعاذة", meaning: "My Lord, I seek refuge in You from asking that of which I have no knowledge", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء نوح عليه السلام", orderIndex: 85, isFeatured: false },
  { phraseAr: "ربنا هب لنا من أزواجنا وذرياتنا قرة أعين", transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yun", translationAr: "دعاء الذرية", meaning: "Our Lord, grant us from our spouses and offspring comfort to our eyes", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة الفرقان", orderIndex: 86, isFeatured: false },
  { phraseAr: "ربنا أتمم لنا نورنا واغفر لنا إنك على كل شيء قدير", transliteration: "Rabbana atmim lana nurana waghfir lana innaka ala kulli shay'in Qadir", translationAr: "دعاء النور والمغفرة", meaning: "Our Lord, perfect for us our light and forgive us", recommendedCount: 7, category: "دعاء", timeOfDay: "general", spiritualNote: "من سورة التحريم", orderIndex: 87, isFeatured: false },
  { phraseAr: "اللهم إني أسألك من الخير كله عاجله وآجله ما علمت منه وما لم أعلم", transliteration: "Allahumma inni as'aluka minal-khayri kullajihi wa ajilihi ma alimtu minhu wa ma lam a'lam", translationAr: "سؤال الخير كله", meaning: "O Allah, I ask You for all good, immediate and future, known and unknown", recommendedCount: 1, category: "دعاء", timeOfDay: "general", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 88, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من الشر كله عاجله وآجله ما علمت منه وما لم أعلم", transliteration: "Allahumma inni a'udhu bika minash-sharri kullajihi wa ajilihi ma alimtu minhu wa ma lam a'lam", translationAr: "الاستعاذة من الشر كله", meaning: "O Allah, I seek refuge from all evil, immediate and future", recommendedCount: 1, category: "استعاذة", timeOfDay: "general", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 89, isFeatured: false },
  { phraseAr: "اللهم إني أسألك من خير ما سألك عبدك ونبيك محمد ﷺ", transliteration: "Allahumma inni as'aluka min khayri ma sa'alaka abduka wa nabiyyuka Muhammad ﷺ", translationAr: "سؤال الخير", meaning: "O Allah, I ask You for the good that Your servant and Prophet Muhammad asked for", recommendedCount: 1, category: "دعاء", timeOfDay: "general", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 90, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من شر ما سألك منه نبيك محمد ﷺ", transliteration: "Allahumma inni a'udhu bika min sharri ma sa'alaka minhu nabiyyuka Muhammad ﷺ", translationAr: "الاستعاذة من الشر", meaning: "O Allah, I seek refuge from the evil that Your Prophet sought refuge from", recommendedCount: 1, category: "استعاذة", timeOfDay: "general", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 91, isFeatured: false },
  { phraseAr: "اللهم إني أسألك الجنة وما قرب إليها من قول أو عمل", transliteration: "Allahumma inni as'alukal-Jannata wa ma qarraba ilayha min qawlin aw amal", translationAr: "سؤال الجنة", meaning: "O Allah, I ask You for Paradise and what draws one closer to it", recommendedCount: 1, category: "دعاء", timeOfDay: "general", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 92, isFeatured: false },
  { phraseAr: "اللهم إني أعوذ بك من النار وما قرب إليها من قول أو عمل", transliteration: "Allahumma inni a'udhu bika minan-Nari wa ma qarraba ilayha min qawlin aw amal", translationAr: "الاستعاذة من النار", meaning: "O Allah, I seek refuge from the Fire and what draws one closer to it", recommendedCount: 1, category: "استعاذة", timeOfDay: "general", spiritualNote: "من أدعية النبي ﷺ", orderIndex: 93, isFeatured: false },
  { phraseAr: "سبحان الله عدد خلقه", transliteration: "SubhanAllahi adada khalqihi", translationAr: "التسبيح", meaning: "Glory be to Allah, by the multitude of His creation", recommendedCount: 33, category: "تسبيح", timeOfDay: "general", spiritualNote: "تعدل ثلاث تسبيحات", orderIndex: 94, isFeatured: false },
  { phraseAr: "سبحان الله رضا نفسه", transliteration: "SubhanAllahi rida nafsihi", translationAr: "التسبيح", meaning: "Glory be to Allah, by His pleasure", recommendedCount: 33, category: "تسبيح", timeOfDay: "general", spiritualNote: "تعدل ثلاث تسبيحات", orderIndex: 95, isFeatured: false },
  { phraseAr: "سبحان الله زنة عرشه", transliteration: "SubhanAllahi zinata arshihi", translationAr: "التسبيح", meaning: "Glory be to Allah, by the weight of His Throne", recommendedCount: 33, category: "تسبيح", timeOfDay: "general", spiritualNote: "تعدل ثلاث تسبيحات", orderIndex: 96, isFeatured: false },
  { phraseAr: "سبحان الله مداد كلماته", transliteration: "SubhanAllahi midada kalimatihi", translationAr: "التسبيح", meaning: "Glory be to Allah, by the ink of His words", recommendedCount: 33, category: "تسبيح", timeOfDay: "general", spiritualNote: "تعدل ثلاث تسبيحات", orderIndex: 97, isFeatured: false },
  { phraseAr: "اللهم اغفر للمسلمين والمسلمات والمؤمنين والمؤمنات الأحياء منهم والأموات", transliteration: "Allahumma-ghfir lil-muslimina wal-muslimat, wal-mu'minina wal-mu'minat, al-ahya'i minhum wal-amwat", translationAr: "دعاء للمسلمين", meaning: "O Allah, forgive the Muslim men and women, the believing men and women, the living and the dead", recommendedCount: 1, category: "دعاء", timeOfDay: "general", spiritualNote: "دعاء شامل للأمة", orderIndex: 98, isFeatured: false },
  { phraseAr: "اللهم اجعل هذا الحج مبروراً وسعياً مشكوراً وذنباً مغفوراً وعملاً صالحاً مقبولاً", transliteration: "Allahumma-ij'al hadhal-hajja mabrura, wa sa'yan mashkura, wa dhanban maghfura, wa amalan salihan maqbula", translationAr: "دعاء الحج", meaning: "O Allah, make this Hajj accepted, effort appreciated, sins forgiven, and deeds accepted", recommendedCount: 1, category: "دعاء الحج", timeOfDay: "general", spiritualNote: "دعاء خاص بالحاج", orderIndex: 99, isFeatured: false },
  { phraseAr: "اللهم ارزقنا زيارة بيتك الحرام ومسجد نبيك الكريم في كل عام", transliteration: "Allahumma-ruzna ziyarata baytikal-haram wa masjida nabiyyikal-karim fi kulli am", translationAr: "دعاء الزيارة", meaning: "O Allah, grant us the visit of Your Sacred House and Your Prophet's Mosque every year", recommendedCount: 1, category: "دعاء الحج", timeOfDay: "general", spiritualNote: "دعاء الحاج والمعتمر", orderIndex: 100, isFeatured: false },
];

async function main() {
  console.log("Seeding tasbih presets...");

  const existing = await db
    .select({ count: count() })
    .from(tasbihPresetsTable);

  const countValue = Number(existing[0]?.count ?? 0);
  if (countValue > 0) {
    console.log(`Already have ${countValue} presets, skipping.`);
    return;
  }

  await db.insert(tasbihPresetsTable).values(PRESETS);
  console.log(`Seeded ${PRESETS.length} tasbih presets.`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
