import { db, duaCategoriesTable, duasTable } from "@workspace/db";
import { eq } from "drizzle-orm";

async function main() {
  console.log("Seeding dua categories and duas...");

  const categories = [
    {
      nameAr: "الإحرام والتلبية",
      nameEn: "Ihram & Talbiyah",
      emoji: "🤍",
      color: "#1D9E75",
      descriptionAr: "نيات الإحرام للأنواع الثلاثة والتلبية وأدعية الميقات",
      orderIndex: 1,
    },
    {
      nameAr: "أدعية مكة المكرمة",
      nameEn: "Makkah Duas",
      emoji: "🕋",
      color: "#0ea5e9",
      descriptionAr: "أدعية دخول مكة ورؤية الكعبة والحجر الأسود وزمزم",
      orderIndex: 2,
    },
    {
      nameAr: "أدعية الطواف",
      nameEn: "Tawaf Duas",
      emoji: "🔄",
      color: "#8b5cf6",
      descriptionAr: "أدعية الأشواط السبعة للطواف حول الكعبة المشرفة",
      orderIndex: 3,
    },
    {
      nameAr: "أدعية السعي",
      nameEn: "Sa'i Duas",
      emoji: "🏃",
      color: "#ec4899",
      descriptionAr: "أدعية السعي بين الصفا والمروة — الأشواط السبعة",
      orderIndex: 4,
    },
    {
      nameAr: "أدعية عرفات",
      nameEn: "Arafah Duas",
      emoji: "🌄",
      color: "#EF9F27",
      descriptionAr: "أفضل وأجمع أدعية يوم عرفة — أعظم أيام الحج",
      orderIndex: 5,
    },
    {
      nameAr: "أدعية مزدلفة ومنى",
      nameEn: "Muzdalifah & Mina Duas",
      emoji: "⛺",
      color: "#6366f1",
      descriptionAr: "أدعية المبيت في مزدلفة وأيام التشريق في منى",
      orderIndex: 6,
    },
    {
      nameAr: "أدعية الجمرات",
      nameEn: "Jamarat Duas",
      emoji: "🪨",
      color: "#E24B4A",
      descriptionAr: "أدعية رمي الجمرات الثلاث والتكبير عند كل جمرة",
      orderIndex: 7,
    },
    {
      nameAr: "أدعية المدينة المنورة",
      nameEn: "Madinah Duas",
      emoji: "🌿",
      color: "#10b981",
      descriptionAr: "أدعية زيارة المدينة المنورة والمسجد النبوي والسلام على النبي ﷺ",
      orderIndex: 8,
    },
    {
      nameAr: "أذكار الصباح والمساء",
      nameEn: "Morning & Evening Adhkar",
      emoji: "🌅",
      color: "#f59e0b",
      descriptionAr: "الأذكار المأثورة في الصباح والمساء من السنة النبوية",
      orderIndex: 9,
    },
    {
      nameAr: "أدعية الصلاة",
      nameEn: "Prayer Duas",
      emoji: "🕌",
      color: "#7c3aed",
      descriptionAr: "الأدعية الواردة في أوقات الصلاة وبعدها",
      orderIndex: 10,
    },
    {
      nameAr: "أدعية جامعة",
      nameEn: "General Duas",
      emoji: "📿",
      color: "#dc2626",
      descriptionAr: "أدعية شاملة من الكتاب والسنة لكل الأحوال",
      orderIndex: 11,
    },
    {
      nameAr: "أدعية الطوارئ والضيق",
      nameEn: "Emergency & Distress Duas",
      emoji: "🤲",
      color: "#e11d48",
      descriptionAr: "أدعية الفرج والتوسل في أوقات الشدة والكرب",
      orderIndex: 12,
    },
    {
      nameAr: "أدعية السفر",
      nameEn: "Travel Duas",
      emoji: "✈️",
      color: "#0284c7",
      descriptionAr: "أدعية الخروج من المنزل والسفر والعودة",
      orderIndex: 13,
    },
    {
      nameAr: "الأدعية الطويلة الكاملة",
      nameEn: "Full Long Duas",
      emoji: "🌟",
      color: "#b45309",
      descriptionAr: "الأدعية الطويلة الكاملة من التراث الإسلامي",
      orderIndex: 14,
    },
  ];

  const catMap: Record<string, string> = {};

  for (const cat of categories) {
    const existing = await db
      .select({ id: duaCategoriesTable.id })
      .from(duaCategoriesTable)
      .where(eq(duaCategoriesTable.nameAr, cat.nameAr))
      .limit(1);

    if (existing.length > 0) {
      catMap[cat.nameAr] = existing[0].id;
      continue;
    }

    const [inserted] = await db
      .insert(duaCategoriesTable)
      .values(cat)
      .returning({ id: duaCategoriesTable.id });
    catMap[cat.nameAr] = inserted.id;
  }

  const duas = [
    // ===== IHRAM & TALBIYAH =====
    {
      titleAr: "نية الإحرام بالإفراد",
      titleEn: "Intention for Ifrad Hajj",
      arabicText: "لَبَّيْكَ اللَّهُمَّ حَجًّا",
      translationAr: "لبيت نداءك يا الله للحج — وهذا لمن أحرم بالحج مفرداً",
      translationEn: "Here I am, O Allah, for Hajj (Ifrad — Hajj only).",
      source: "صحيح البخاري ومسلم",
      categoryName: "الإحرام والتلبية",
      mansakKey: "ihram",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "نية الإحرام بالتمتع",
      titleEn: "Intention for Tamattu Hajj",
      arabicText: "لَبَّيْكَ اللَّهُمَّ عُمْرَةً مُتَمَتِّعًا بِهَا إِلَى الْحَجِّ",
      translationAr: "لبيت نداءك يا الله بعمرة متمتعاً بها إلى الحج",
      translationEn: "Here I am, O Allah, for Umrah followed by Hajj (Tamattu).",
      source: "السنة النبوية",
      categoryName: "الإحرام والتلبية",
      mansakKey: "ihram",
      isFeatured: false,
      orderIndex: 2,
    },
    {
      titleAr: "نية الإحرام بالقران",
      titleEn: "Intention for Qiran Hajj",
      arabicText: "لَبَّيْكَ اللَّهُمَّ بِحَجٍّ وَعُمْرَةٍ مَعًا",
      translationAr: "لبيت نداءك يا الله بحج وعمرة معاً — وهذا للقارن",
      translationEn: "Here I am, O Allah, for Hajj and Umrah together (Qiran).",
      source: "صحيح مسلم",
      categoryName: "الإحرام والتلبية",
      mansakKey: "ihram",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "التلبية",
      titleEn: "Talbiyah",
      arabicText: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لاَ شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لاَ شَرِيكَ لَكَ",
      translationAr: "لبيت نداءك يا الله، لبيت وأنا عبدك، لا شريك لك في ربوبيتك وألوهيتك، إن الحمد كله لك والنعمة كلها منك والملك كله ملكك، لا شريك لك",
      translationEn: "Here I am, O Allah, here I am. Here I am, You have no partner, here I am. Verily all praise and blessings are Yours, and all sovereignty. You have no partner.",
      source: "البخاري ومسلم",
      categoryName: "الإحرام والتلبية",
      mansakKey: "ihram",
      isFeatured: true,
      orderIndex: 4,
    },
    {
      titleAr: "دعاء الإحرام بعد ركعتين",
      titleEn: "Dua after two Rakats at Miqat",
      arabicText: "اللَّهُمَّ إِنِّي أُرِيدُ الْحَجَّ فَيَسِّرْهُ لِي وَتَقَبَّلْهُ مِنِّي",
      translationAr: "اللهم إني أريد الحج فيسّره لي وتقبله مني",
      translationEn: "O Allah, I intend to perform Hajj, so make it easy for me and accept it from me.",
      source: "السنة النبوية",
      categoryName: "الإحرام والتلبية",
      mansakKey: "ihram",
      isFeatured: false,
      orderIndex: 5,
    },
    {
      titleAr: "دعاء الميقات للمحصر",
      titleEn: "Dua of Conditional Ihram",
      arabicText: "اللَّهُمَّ مَحِلِّي حَيْثُ حَبَسْتَنِي",
      translationAr: "اللهم أحلّ إحرامي حيث حبستني عن إتمام نسكي",
      translationEn: "O Allah, my place of release from Ihram is wherever You prevent me from completing it.",
      source: "صحيح البخاري",
      categoryName: "الإحرام والتلبية",
      mansakKey: "ihram",
      isFeatured: false,
      orderIndex: 6,
    },

    // ===== MAKKAH DUAS =====
    {
      titleAr: "دعاء دخول مكة المكرمة",
      titleEn: "Dua for Entering Makkah",
      arabicText: "اللَّهُمَّ هَذَا حَرَمُكَ وَأَمْنُكَ، فَحَرِّمْنِي عَلَى النَّارِ، وَأَمِّنِّي مِنْ عَذَابِكَ يَوْمَ تَبْعَثُ عِبَادَكَ، وَاجْعَلْنِي مِنْ أَوْلِيَائِكَ وَأَهْلِ طَاعَتِكَ",
      translationAr: "اللهم هذا حرمك وأمانك، فحرّمني على النار وأمّنّي من عذابك يوم تبعث عبادك، واجعلني من أوليائك وأهل طاعتك",
      translationEn: "O Allah, this is Your sanctuary and Your place of security, so make me forbidden to the Fire, secure me from Your punishment on the Day You raise Your servants, and make me among Your loyal servants.",
      source: "السنة النبوية",
      categoryName: "أدعية مكة المكرمة",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء رؤية الكعبة المشرفة أول مرة",
      titleEn: "Dua upon First Sight of the Kaaba",
      arabicText: "اللَّهُمَّ زِدْ هَذَا الْبَيْتَ تَشْرِيفًا وَتَعْظِيمًا وَتَكْرِيمًا وَمَهَابَةً، وَزِدْ مَنْ شَرَّفَهُ وَكَرَّمَهُ مِمَّنْ حَجَّهُ أَوِ اعْتَمَرَهُ تَشْرِيفًا وَتَكْرِيمًا وَتَعْظِيمًا وَبِرًّا",
      translationAr: "اللهم زد هذا البيت شرفاً وعظمةً وكرامةً ومهابةً، وزد من شرّفه ممن حجّه أو اعتمره شرفاً وكرامةً وتعظيماً وبراً",
      translationEn: "O Allah, increase this House in honor, greatness, nobility, and reverence. And increase those who honor it — among those who perform Hajj or Umrah — in honor, nobility, greatness and righteousness.",
      source: "رواه الشافعي",
      categoryName: "أدعية مكة المكرمة",
      mansakKey: "tawaf_qudum",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء الدخول من باب السلام",
      titleEn: "Dua at Bab Al-Salam",
      arabicText: "بِسْمِ اللَّهِ وَالصَّلاَةُ وَالسَّلاَمُ عَلَى رَسُولِ اللَّهِ، اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
      translationAr: "بسم الله والصلاة والسلام على رسول الله، اللهم افتح لي أبواب رحمتك",
      translationEn: "In the name of Allah, and peace and blessings upon the Messenger of Allah. O Allah, open for me the gates of Your mercy.",
      source: "السنة النبوية",
      categoryName: "أدعية مكة المكرمة",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "دعاء شرب ماء زمزم",
      titleEn: "Dua when Drinking Zamzam",
      arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا وَاسِعًا وَشِفَاءً مِنْ كُلِّ دَاءٍ",
      translationAr: "اللهم إني أسألك علماً نافعاً ورزقاً واسعاً وشفاءً من كل داء",
      translationEn: "O Allah, I ask You for beneficial knowledge, abundant provision, and cure from all illness.",
      source: "الدارقطني — ماء زمزم لما شُرب له",
      categoryName: "أدعية مكة المكرمة",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "التكبير عند الحجر الأسود",
      titleEn: "Takbir at the Black Stone",
      arabicText: "بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ",
      translationAr: "بسم الله والله أكبر — يُقال عند استلام الحجر الأسود أو الإشارة إليه",
      translationEn: "In the name of Allah, and Allah is the Greatest — said when touching or pointing toward the Black Stone.",
      source: "البخاري",
      categoryName: "أدعية مكة المكرمة",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 5,
    },
    {
      titleAr: "دعاء المقام الإبراهيمي",
      titleEn: "Dua at Maqam Ibrahim",
      arabicText: "وَاتَّخِذُوا مِن مَّقَامِ إِبْرَاهِيمَ مُصَلًّى",
      translationAr: "ويُصلي ركعتين خلف المقام ويقرأ في الأولى: قل يا أيها الكافرون، وفي الثانية: قل هو الله أحد",
      translationEn: "Take the station of Ibrahim as a place of prayer — after which two rakahs are prayed.",
      source: "القرآن — البقرة: ١٢٥",
      categoryName: "أدعية مكة المكرمة",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 6,
    },

    // ===== TAWAF DUAS =====
    {
      titleAr: "دعاء الشوط الأول من الطواف",
      titleEn: "First Circuit of Tawaf",
      arabicText: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلاَ إِلَهَ إِلاَّ اللَّهُ وَاللَّهُ أَكْبَرُ، وَلاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ، اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَاعْفُ عَنِّي وَاهْدِنِي وَارْزُقْنِي",
      translationAr: "سبحان الله والحمد لله ولا إله إلا الله والله أكبر ولا حول ولا قوة إلا بالله. اللهم اغفر لي وارحمني واعف عني واهدني وارزقني",
      translationEn: "Glory be to Allah, praise be to Allah, there is no god but Allah, Allah is the Greatest, there is no power except with Allah. O Allah, forgive me, have mercy on me, pardon me, guide me, and provide for me.",
      source: "السنة النبوية",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء بين الركن اليماني والحجر الأسود",
      titleEn: "Dua Between Yemeni Corner and Black Stone",
      arabicText: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ، وَأَدْخِلْنَا الْجَنَّةَ مَعَ الأَبْرَارِ، يَا عَزِيزُ يَا غَفَّارُ",
      translationAr: "ربنا أعطنا في الدنيا خيراً وفي الآخرة خيراً وقنا عذاب النار، وأدخلنا الجنة مع الأبرار يا عزيز يا غفار",
      translationEn: "Our Lord, grant us good in this world and good in the Hereafter, and protect us from the punishment of the Fire. Enter us into Paradise with the righteous, O Mighty, O Forgiving.",
      source: "أبو داود — الآية: البقرة ٢٠١",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء الشوط الثاني من الطواف",
      titleEn: "Second Circuit of Tawaf",
      arabicText: "اللَّهُمَّ إِنَّكَ قُلْتَ فِي كِتَابِكَ الْمُنَزَّلِ: ادْعُونِي أَسْتَجِبْ لَكُمْ، وَإِنَّكَ لاَ تُخْلِفُ الْمِيعَادَ، وَإِنِّي أَسْأَلُكَ كَمَا هَدَيْتَنِي إِلَى الإِسْلامِ أَلاَّ تَنْزِعَهُ مِنِّي",
      translationAr: "اللهم إنك قلت في كتابك: ادعوني أستجب لكم، وإنك لا تخلف الميعاد. وإني أسألك كما هديتني للإسلام أن لا تنزعه مني حتى تتوفاني عليه",
      translationEn: "O Allah, You said in Your revealed Book: Call upon Me and I will respond to you. You do not break Your promise. I ask You, just as You guided me to Islam, not to take it from me until You cause me to die upon it.",
      source: "المأثور",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "دعاء الشوط الثالث من الطواف",
      titleEn: "Third Circuit of Tawaf",
      arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الشِّرْكِ وَالشِّقَاقِ وَالنِّفَاقِ، وَسُوءِ الأَخْلاَقِ، وَسُوءِ الْمَنْظَرِ وَالْمُنْقَلَبِ فِي الْمَالِ وَالأَهْلِ وَالْوَلَدِ",
      translationAr: "اللهم إني أعوذ بك من الشرك والشقاق والنفاق وسوء الأخلاق وسوء المنظر والمنقلب في المال والأهل والولد",
      translationEn: "O Allah, I seek refuge in You from shirk, discord, hypocrisy, bad manners, and evil return in wealth, family and children.",
      source: "المأثور",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "دعاء الشوط الرابع من الطواف",
      titleEn: "Fourth Circuit of Tawaf",
      arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ وَالْمُعَافَاةَ الدَّائِمَةَ فِي الدِّينِ وَالدُّنْيَا وَالآخِرَةِ",
      translationAr: "اللهم إني أسألك العفو والعافية والمعافاة الدائمة في الدين والدنيا والآخرة",
      translationEn: "O Allah, I ask You for pardon, health, and lasting well-being in religion, this world, and the Hereafter.",
      source: "المأثور",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 5,
    },
    {
      titleAr: "دعاء الشوط الخامس من الطواف",
      titleEn: "Fifth Circuit of Tawaf",
      arabicText: "اللَّهُمَّ اجْعَلْ حَجِّي مَبْرُورًا وَسَعْيِي مَشْكُورًا وَذَنْبِي مَغْفُورًا وَعَمَلِي صَالِحًا مَقْبُولًا وَتِجَارَتِي لَنْ تَبُورَ",
      translationAr: "اللهم اجعل حجي مبروراً وسعيي مشكوراً وذنبي مغفوراً وعملي صالحاً مقبولاً وتجارتي لن تبور",
      translationEn: "O Allah, make my Hajj accepted, my Sa'i thanked, my sin forgiven, my deeds righteous and accepted, and my trade never bankrupt.",
      source: "المأثور",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 6,
    },
    {
      titleAr: "دعاء الشوط السادس من الطواف",
      titleEn: "Sixth Circuit of Tawaf",
      arabicText: "اللَّهُمَّ إِنَّ لَكَ عَلَيَّ حُقُوقًا فَتَصَدَّقْ بِهَا عَلَيَّ، وَلِلنَّاسِ قِبَلِي تَبِعَاتٌ فَتَحَمَّلْهَا عَنِّي، وَأَغْنِنِي بِحَلاَلِكَ عَنْ حَرَامِكَ، وَبِطَاعَتِكَ عَنْ مَعْصِيَتِكَ، وَبِفَضْلِكَ عَمَّنْ سِوَاكَ",
      translationAr: "اللهم إن لك علي حقوقاً فتصدق بها عليّ، وللناس قِبَلي تبعاتٌ فتحمّلها عني. وأغنني بحلالك عن حرامك، وبطاعتك عن معصيتك، وبفضلك عمن سواك",
      translationEn: "O Allah, You have rights over me so grant them to me as charity. People have claims against me, so bear them for me. Make me self-sufficient with Your lawful provision over the forbidden, with Your obedience over disobedience, and with Your favor over others.",
      source: "المأثور",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 7,
    },
    {
      titleAr: "دعاء الشوط السابع من الطواف",
      titleEn: "Seventh Circuit of Tawaf",
      arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ إِيمَانًا كَامِلًا وَيَقِينًا صَادِقًا وَرِزْقًا وَاسِعًا وَحَلاَلًا طَيِّبًا وَتَوْبَةً نَصُوحًا وَلِسَانًا ذَاكِرًا وَتَوْبَةً قَبْلَ الْمَوْتِ وَرَاحَةً عِنْدَ الْمَوْتِ وَمَغْفِرَةً وَرَحْمَةً بَعْدَ الْمَوْتِ وَالْعَفْوَ عِنْدَ الْحِسَابِ",
      translationAr: "اللهم إني أسألك إيماناً كاملاً ويقيناً صادقاً ورزقاً واسعاً حلالاً طيباً وتوبةً نصوحاً ولساناً ذاكراً وتوبةً قبل الموت وراحةً عند الموت ومغفرةً ورحمةً بعد الموت والعفو عند الحساب",
      translationEn: "O Allah, I ask You for complete faith, sincere conviction, abundant lawful provision, a sincere repentance, a tongue that remembers, repentance before death, ease at death, forgiveness and mercy after death, and pardon at the reckoning.",
      source: "المأثور",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_qudum",
      isFeatured: false,
      orderIndex: 8,
    },
    {
      titleAr: "دعاء طواف الوداع",
      titleEn: "Farewell Tawaf Dua",
      arabicText: "اللَّهُمَّ الْبَيْتُ بَيْتُكَ، وَالْعَبْدُ عَبْدُكَ، وَابْنُ عَبْدِكَ، وَابْنُ أَمَتِكَ، حَمَلْتَنِي عَلَى مَا سَخَّرْتَ لِي مِنْ خَلْقِكَ، وَسَيَّرْتَنِي فِي بِلاَدِكَ، حَتَّى بَلَّغْتَنِي بِنِعْمَتِكَ إِلَى بَيْتِكَ، وَأَعَنْتَنِي عَلَى أَدَاءِ نُسُكِي، فَإِنْ كُنْتَ رَضِيتَ عَنِّي فَازْدَدْ عَنِّي رِضًا، وَإِلاَّ فَمِنَ الآنَ فَارْضَ عَنِّي قَبْلَ أَنْ تَنْأَى عَنْ بَيْتِكَ دَارِي",
      translationAr: "اللهم البيت بيتك والعبد عبدك وابن عبدك وابن أمتك. حملتني على ما سخّرت لي من خلقك وسيّرتني في بلادك حتى أوصلتني بنعمتك إلى بيتك وأعنتني على أداء نسكي. فإن كنت رضيت عني فزدني رضاً، وإلا فمن الآن فارضَ عني قبل أن تبعد عن بيتك داري",
      translationEn: "O Allah, the House is Your House, and the servant is Your servant, son of Your servant, son of Your maidservant. You carried me upon what You subjugated for me of Your creation, and made me travel through Your lands until You brought me with Your blessing to Your House, and helped me perform my rituals.",
      source: "الأذكار للنووي",
      categoryName: "أدعية الطواف",
      mansakKey: "tawaf_wada",
      isFeatured: false,
      orderIndex: 9,
    },

    // ===== SA'I DUAS =====
    {
      titleAr: "دعاء الصعود على الصفا",
      titleEn: "Dua at Mount Safa",
      arabicText: "إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ، أَبْدَأُ بِمَا بَدَأَ اللَّهُ بِهِ",
      translationAr: "إن الصفا والمروة من شعائر الله — ثم يبدأ بالصفا قائلاً: أبدأ بما بدأ الله به",
      translationEn: "Indeed Safa and Marwah are among the symbols of Allah — then he begins at Safa, saying: I begin with what Allah began with.",
      source: "صحيح مسلم",
      categoryName: "أدعية السعي",
      mansakKey: "sai",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء الصفا والمروة",
      titleEn: "Dua on Safa and Marwah",
      arabicText: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، أَنْجَزَ وَعْدَهُ، وَنَصَرَ عَبْدَهُ، وَهَزَمَ الأَحْزَابَ وَحْدَهُ",
      translationAr: "الله أكبر، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد، يحيي ويميت، وهو على كل شيء قدير. وفى وعده، ونصر عبده، وهزم الأحزاب وحده",
      translationEn: "Allah is Greatest. There is no god but Allah alone, without partner. To Him belongs dominion and all praise. He gives life and causes death. He is Powerful over all things. He fulfilled His promise, gave victory to His servant, and alone defeated the confederates.",
      source: "صحيح مسلم",
      categoryName: "أدعية السعي",
      mansakKey: "sai",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء في السعي بين الصفا والمروة",
      titleEn: "Dua During Sa'i Walk",
      arabicText: "رَبِّ اغْفِرْ وَارْحَمْ وَاعْفُ وَتَكَرَّمْ وَتَجَاوَزْ عَمَّا تَعْلَمُ، إِنَّكَ تَعْلَمُ مَا لاَ نَعْلَمُ، إِنَّكَ أَنْتَ اللَّهُ الأَعَزُّ الأَكْرَمُ",
      translationAr: "ربي اغفر وارحم واعف وتكرم وتجاوز عما تعلم، إنك تعلم ما لا نعلم، إنك أنت الله الأعز الأكرم",
      translationEn: "My Lord, forgive, have mercy, pardon, be generous and overlook what You know. You know what we do not know. You are Allah, the Most Mighty, the Most Generous.",
      source: "المأثور — يُقال في بداية الخبب بين الميلين الأخضرين",
      categoryName: "أدعية السعي",
      mansakKey: "sai",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "دعاء الشوط الثاني من السعي",
      titleEn: "Second Lap of Sa'i",
      arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الرَّضَا بَعْدَ الْقَضَاءِ، وَبَرْدَ الْعَيْشِ بَعْدَ الْمَوْتِ، وَلَذَّةَ النَّظَرِ إِلَى وَجْهِكَ، وَالشَّوْقَ إِلَى لِقَائِكَ مِنْ غَيْرِ ضَرَّاءَ مُضِرَّةٍ وَلاَ فِتْنَةٍ مُضِلَّةٍ",
      translationAr: "اللهم إني أسألك الرضا بعد القضاء وبرد العيش بعد الموت ولذة النظر إلى وجهك والشوق إلى لقائك من غير ضراء مضرة ولا فتنة مضلة",
      translationEn: "O Allah, I ask You for contentment after Your decree, the coolness of life after death, the delight of looking at Your Face, and longing to meet You without harmful affliction or misleading trial.",
      source: "السنة النبوية",
      categoryName: "أدعية السعي",
      mansakKey: "sai",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "دعاء الشوط الثالث من السعي",
      titleEn: "Third Lap of Sa'i",
      arabicText: "رَبِّ زِدْنِي عِلْمًا وَلاَ تُزِغْ قَلْبِي بَعْدَ إِذْ هَدَيْتَنِي، وَهَبْ لِي مِنْ لَدُنْكَ رَحْمَةً، إِنَّكَ أَنْتَ الْوَهَّابُ",
      translationAr: "ربي زدني علماً ولا تُزِغ قلبي بعد إذ هديتني وهب لي من لدنك رحمة إنك أنت الوهاب",
      translationEn: "My Lord, increase me in knowledge. Do not let my heart deviate after You have guided me, and grant me from Yourself mercy. Indeed You are the Bestower.",
      source: "القرآن — طه: ١١٤، آل عمران: ٨",
      categoryName: "أدعية السعي",
      mansakKey: "sai",
      isFeatured: false,
      orderIndex: 5,
    },
    {
      titleAr: "دعاء الشوط السابع من السعي — ختام",
      titleEn: "Seventh Lap of Sa'i — Completion",
      arabicText: "اللَّهُمَّ تَقَبَّلْ مِنِّي، وَاجْعَلْ حَجِّي مَبْرُورًا وَسَعْيِي مَشْكُورًا وَذَنْبِي مَغْفُورًا، بِرَحْمَتِكَ يَا أَرْحَمَ الرَّاحِمِينَ",
      translationAr: "اللهم تقبل مني، واجعل حجي مبروراً وسعيي مشكوراً وذنبي مغفوراً، برحمتك يا أرحم الراحمين",
      translationEn: "O Allah, accept from me, and make my Hajj accepted, my Sa'i thanked, and my sin forgiven, by Your mercy O Most Merciful of the merciful.",
      source: "المأثور",
      categoryName: "أدعية السعي",
      mansakKey: "sai",
      isFeatured: false,
      orderIndex: 7,
    },

    // ===== ARAFAH DUAS =====
    {
      titleAr: "أفضل دعاء يوم عرفة",
      titleEn: "Best Dua on Day of Arafah",
      arabicText: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
      translationAr: "لا إله إلا الله وحده لا شريك له، له الملك وله الحمد، وهو على كل شيء قدير",
      translationEn: "There is no god but Allah alone, without partner. To Him belongs all dominion and all praise, and He is capable of all things.",
      source: "الترمذي — خير الدعاء دعاء يوم عرفة",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: true,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء عرفة الجامع",
      titleEn: "Comprehensive Dua at Arafah",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ كَالَّذِي نَقُولُ وَخَيْرًا مِمَّا نَقُولُ، اللَّهُمَّ لَكَ صَلاَتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي، وَإِلَيْكَ مَآبِي، وَلَكَ تُرَاثِي، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، وَوَسْوَسَةِ الصَّدْرِ، وَشَتَاتِ الأَمْرِ",
      translationAr: "اللهم لك الحمد كما نقول وأحسن مما نقول. اللهم لك صلاتي ونسكي وحياتي ومماتي وإليك مرجعي. اللهم إني أعوذ بك من عذاب القبر ووسوسة الصدر وتشتت الأمر",
      translationEn: "O Allah, to You belongs all praise as we say and better than what we say. O Allah, my prayer, my worship, my life and my death are for You, and to You is my return. O Allah, I seek refuge in You from the punishment of the grave, the whispers of the chest, and the scattering of affairs.",
      source: "ابن السني",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء عرفة: المغفرة والرحمة",
      titleEn: "Arafah Dua for Forgiveness",
      arabicText: "اللَّهُمَّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ يَوْمَ يَقُومُ الْحِسَابُ، اللَّهُمَّ أَظِلَّنِي تَحْتَ ظِلِّ عَرْشِكَ يَوْمَ لاَ ظِلَّ إِلاَّ ظِلُّكَ",
      translationAr: "اللهم اغفر لي ولوالدي وللمؤمنين والمؤمنات يوم يقوم الحساب. اللهم أظلني تحت ظل عرشك يوم لا ظل إلا ظلك",
      translationEn: "O Allah, forgive me and my parents and the believing men and women on the Day the reckoning is established. O Allah, shade me under Your Throne on the Day when there is no shade except Yours.",
      source: "المأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "دعاء عرفة: قبول الحج",
      titleEn: "Arafah Dua for Accepted Hajj",
      arabicText: "اللَّهُمَّ تَقَبَّلْ طَوَافِي وَاجْعَلْ سَعْيِي مَشْكُورًا وَذَنْبِي مَغْفُورًا، اللَّهُمَّ عَبْدُكَ فَقِيرٌ إِلَى رَحْمَتِكَ، وَأَنْتَ غَنِيٌّ عَنْ عَذَابِي، اللَّهُمَّ اجْعَلْ حَجِّي مَبْرُورًا",
      translationAr: "اللهم تقبل طوافي واجعل سعيي مشكوراً وذنبي مغفوراً. اللهم عبدك فقير إلى رحمتك وأنت غني عن عذابي. اللهم اجعل حجي مبروراً",
      translationEn: "O Allah, accept my Tawaf, make my Sa'i thanked and my sin forgiven. O Allah, Your servant is in need of Your mercy, and You are free from needing to punish me. O Allah, make my Hajj accepted.",
      source: "المأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "دعاء عرفة الطويل الكامل",
      titleEn: "Long Comprehensive Dua of Arafah",
      arabicText: "اللَّهُمَّ إِنَّا نَسْأَلُكَ مِنَ النِّعْمَةِ تَمَامَهَا، وَمِنَ الْعِصْمَةِ دَوَامَهَا، وَمِنَ الرَّحْمَةِ شُمُولَهَا، وَمِنَ الْعَافِيَةِ حُصُولَهَا، وَمِنَ الْعَيْشِ أَرْغَدَهُ، وَمِنَ الْعُمُرِ أَسْعَدَهُ، وَمِنَ الإِحْسَانِ أَتَمَّهُ، وَمِنَ الْفَضْلِ أَعْذَبَهُ، وَمِنَ اللُّطْفِ أَقْرَبَهُ، كُنْ لَنَا وَلاَ تَكُنْ عَلَيْنَا، وَاخْتِمْ بِالسَّعَادَةِ آجَالَنَا",
      translationAr: "اللهم إنا نسألك من النعمة تمامها ومن العصمة دوامها ومن الرحمة شمولها ومن العافية حصولها ومن العيش أرغده ومن العمر أسعده ومن الإحسان أتمه ومن الفضل أعذبه ومن اللطف أقربه. كن لنا ولا تكن علينا، واختم بالسعادة آجالنا",
      translationEn: "O Allah, we ask You for the completion of blessings, the permanence of protection, the encompassment of mercy, the attainment of well-being, the most abundant of lives, the happiest of lifespans, the most complete of kindness, the sweetest of favors, and the closest of gentleness. Be for us and not against us, and seal our lives with happiness.",
      source: "المأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 5,
    },
    {
      titleAr: "دعاء عرفة: الرضا والشكر",
      titleEn: "Arafah Dua of Gratitude",
      arabicText: "اللَّهُمَّ إِنَّا نَسْأَلُكَ الْحَمْدَ لَكَ وَالرِّضَا عَنْكَ، وَالسُّكُونَ إِلَيْكَ، وَالثِّقَةَ بِكَ، وَالْقَرَارَ مَعَكَ، فَإِنَّ فِي الْحَمْدِ زِيَادَةً، وَفِي الرِّضَا عَنْكَ قُرْبَةً، وَفِي السُّكُونِ إِلَيْكَ تَوَكُّلًا، وَفِي الثِّقَةِ بِكَ إِخْلاَصًا",
      translationAr: "اللهم إنا نسألك الحمد لك والرضا عنك والسكون إليك والثقة بك والقرار معك. فإن في الحمد زيادةً وفي الرضا عنك قربةً وفي السكون إليك توكلاً وفي الثقة بك إخلاصاً",
      translationEn: "O Allah, we ask You for praise of You, contentment with You, tranquility with You, trust in You, and settlement with You. For in praise is increase, in contentment is nearness, in tranquility is reliance, and in trust is sincerity.",
      source: "المأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      orderIndex: 6,
    },
    {
      titleAr: "دعاء طويل للعائلة والأهل والأخوات",
      titleEn: "Long Dua for Family and Siblings",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ، الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ، وَالْحَمْدُ لِلَّهِ الَّذِي جَمَعَنَا بِالأَهْلِ وَالأَحْبَابِ وَجَعَلَ بَيْنَنَا مَوَدَّةً وَرَحْمَةً.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.\n\nاللَّهُمَّ احْفَظْ عَائِلَتِي وَأَهْلِي وَأَخَوَاتِي وَإِخْوَتِي وَكُلَّ مَنْ أُحِبُّ، حِفْظًا يَلِيقُ بِعَظَمَتِكَ وَرَحْمَتِكَ يَا رَبَّ الْعَالَمِينَ.\n\nاللَّهُمَّ اجْعَلْ بُيُوتَنَا عَامِرَةً بِالإِيمَانِ وَالسَّكِينَةِ وَالطَّمَأْنِينَةِ، وَابْعَدْ عَنْهَا الْحَزَنَ وَالْمَشَاكِلَ وَالْفُرْقَةَ وَالْهُمُومَ.\n\nاللَّهُمَّ ارْزُقْ أَهْلِي الصِّحَّةَ وَالْعَافِيَةَ وَطُولَ الْعُمُرِ فِي طَاعَتِكَ، وَبَارِكْ لَهُمْ فِي أَرْزَاقِهِمْ وَأَوْقَاتِهِمْ وَأَيَّامِهِمْ.\n\nاللَّهُمَّ إِنْ كَانَ فِي قُلُوبِهِمْ تَعَبٌ فَأَرِحْهُمْ، وَإِنْ كَانَ فِي صُدُورِهِمْ هَمٌّ فَفَرِّجْهُ، وَإِنْ كَانَ فِي أَجْسَادِهِمْ مَرَضٌ فَاشْفِهِمْ شِفَاءً لاَ يُغَادِرُ سَقَمًا.\n\nاللَّهُمَّ احْفَظْ وَالِدَيَّ بِعَيْنِكَ الَّتِي لاَ تَنَامُ، وَارْزُقْهُمَا رَاحَةَ الْبَالِ وَسَعَادَةَ الدُّنْيَا وَالآخِرَةِ.\n\nاللَّهُمَّ اجْزِ أُمِّي عَنِّي خَيْرَ الْجَزَاءِ، وَارْزُقْهَا الصِّحَّةَ وَالْعَافِيَةَ وَالسَّعَادَةَ، وَبَارِكْ لَهَا فِي عُمْرِهَا وَرِزْقِهَا وَقَلْبِهَا.\n\nاللَّهُمَّ وَارْحَمْ أَبِي وَوَفِّقْهُ وَبَارِكْ لَهُ وَوَسِّعْ عَلَيْهِ، وَاجْعَلْهُ مِنْ أَسْعَدِ عِبَادِكَ فِي الدُّنْيَا وَالآخِرَةِ.\n\nاللَّهُمَّ احْفَظْ أَخَوَاتِي وَإِخْوَتِي مِنْ كُلِّ سُوءٍ، وَاكْتُبْ لَهُمُ التَّوْفِيقَ وَالنَّجَاحَ وَالسَّعَادَةَ وَالرِّزْقَ الْحَلاَلَ الْمُبَارَكَ.\n\nاللَّهُمَّ ارْزُقْهُمْ رَاحَةً فِي الْقَلْبِ، وَطَمْأَنِينَةً فِي النَّفْسِ، وَنُورًا فِي الطَّرِيقِ، وَتَيْسِيرًا فِي كُلِّ أَمْرٍ.\n\nاللَّهُمَّ اجْعَلْ بَيْنَنَا الْمَحَبَّةَ وَالرَّحْمَةَ وَالْمَوَدَّةَ، وَلاَ تَجْعَلْ لِلشَّيْطَانِ بَيْنَنَا طَرِيقًا.\n\nاللَّهُمَّ ارْزُقْنَا بِرَّ بَعْضِنَا الْبَعْضَ، وَاجْعَلْنَا سَنَدًا وَعَوْنًا لِبَعْضِنَا فِي الدُّنْيَا وَالآخِرَةِ.\n\nاللَّهُمَّ إِنَّا نَسْتَوْدِعُكَ أَهْلَنَا وَأَحْبَابَنَا، فَاحْفَظْهُمْ مِنْ كُلِّ شَرٍّ وَبَلاَءٍ وَمَرَضٍ وَحَزَنٍ.\n\nاللَّهُمَّ لاَ تُرِنَا فِيهِمْ بَأْسًا يُبْكِينَا، وَلاَ هَمًّا يُوجِعُ قُلُوبَنَا.\n\nاللَّهُمَّ اجْمَعْنَا دَائِمًا عَلَى الْخَيْرِ وَالطَّاعَةِ وَالْمَحَبَّةِ، وَاجْعَلْ خَاتِمَتَنَا جَمِيعًا شَهَادَةَ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ.\n\nاللَّهُمَّ ارْزُقْ عَائِلَتِي الْجَنَّةَ بِغَيْرِ حِسَابٍ، وَاجْعَلْنَا مِنَ الْمُتَحَابِّينَ فِيكَ الَّذِينَ يُظِلُّهُمُ اللَّهُ فِي ظِلِّهِ يَوْمَ لاَ ظِلَّ إِلاَّ ظِلُّهُ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم لك الحمد كثيرًا طيبًا مباركًا فيه، الحمد لله الذي بنعمته تتم الصالحات، وجمعنا بالأهل والأحباب. اللهم صل وسلم على سيدنا محمد. اللهم احفظ عائلتي وأهلي وأخواتي وإخوتي وكل من أحب. اللهم اجعل بيوتنا عامرة بالإيمان والسكينة. اللهم ارزق أهلي الصحة والعافية وطول العمر. اللهم ارحم والدتي وأبي وبارك لهما. اللهم احفظ أخواتي وإخوتي. اللهم اجعلنا سندًا لبعضنا. اللهم استودعناك أهلنا وأحبابنا فاحفظهم. اللهم ارزق عائلتي الجنة.",
      translationEn: "O Allah, to You belongs all praise, abundant, good and blessed. Praise be to Allah by Whose grace good deeds are completed. O Allah, send prayers upon our master Muhammad. O Allah, protect my family, relatives, sisters, brothers, and everyone I love with protection befitting Your greatness. O Allah, make our homes filled with faith and tranquility. O Allah, grant my family health, well-being, and long life in Your obedience. O Allah, have mercy on my mother and father and bless them. O Allah, protect my siblings from all evil. O Allah, make us a support for one another. O Allah, we entrust to You our family and loved ones, so protect them. O Allah, grant my family Paradise without reckoning.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 7,
    },
    {
      titleAr: "دعاء للأصدقاء والأحباب",
      titleEn: "Dua for Friends and Loved Ones",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ عَلَى نِعْمَةِ الصُّحْبَةِ الطَّيِّبَةِ وَالْقُلُوبِ الصَّادِقَةِ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلِّمْ.\n\nاللَّهُمَّ احْفَظْ أَصْدِقَائِي وَأَحِبَّتِي أَيْنَمَا كَانُوا، وَبَارِكْ لَهُمْ فِي أَعْمَارِهِمْ وَأَرْزَاقِهِمْ وَصِحَّتِهِمْ.\n\nاللَّهُمَّ ارْزُقْهُمُ السَّعَادَةَ وَالرَّاحَةَ وَالطَّمَأْنِينَةَ، وَافْتَحْ لَهُمْ أَبْوَابَ الْخَيْرِ وَالتَّوْفِيقِ وَالرِّزْقِ.\n\nاللَّهُمَّ إِنْ كَانَ فِي قُلُوبِهِمْ حَزَنٌ فَأَبْدِلْهُ فَرَحًا، وَإِنْ كَانَ فِي حَيَاتِهِمْ ضِيقٌ فَافْتَحْ لَهُمْ أَبْوَابَ الْفَرَجِ.\n\nاللَّهُمَّ اجْعَلْهُمْ مِنْ عِبَادِكَ الصَّالِحِينَ الْمَقْبُولِينَ، وَوَفِّقْهُمْ لِمَا تُحِبُّ وَتَرْضَى.\n\nاللَّهُمَّ أَبْعِدْ عَنْهُمُ الْحَسَدَ وَالشَّرَّ وَالْخُذْلاَنَ وَسُوءَ الأَقْدَارِ.\n\nاللَّهُمَّ ارْزُقْهُمْ رَاحَةَ الْبَالِ، وَهُدُوءَ النَّفْسِ، وَجَمَالَ الأَيَّامِ الْقَادِمَةِ.\n\nاللَّهُمَّ إِنَّ لِي أَصْدِقَاءَ أُحِبُّهُمْ فِيكَ، فَاحْفَظْهُمْ بِعَيْنِكَ الَّتِي لاَ تَنَامُ، وَاكْتُبْ لَهُمُ الْخَيْرَ حَيْثُ كَانَ.\n\nاللَّهُمَّ اجْمَعْنِي بِهِمْ دَائِمًا عَلَى الطَّاعَةِ وَالْخَيْرِ وَالْمَحَبَّةِ الصَّادِقَةِ.\n\nاللَّهُمَّ ارْزُقْنَا جَمِيعًا حُسْنَ الْخَاتِمَةِ وَالْفِرْدَوْسَ الأَعْلَى.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم لك الحمد على نعمة الصحبة الطيبة والقلوب الصادقة. اللهم احفظ أصدقائي وأحبتي أينما كانوا. اللهم ارزقهم السعادة والراحة والطمأنينة. اللهم أبعد عنهم الحسد والشر. اللهم اجمعنا دائمًا على الخير والطاعة.",
      translationEn: "O Allah, praise be to You for the blessing of good companionship and sincere hearts. O Allah, protect my friends and loved ones wherever they are. O Allah, grant them happiness, comfort and tranquility. O Allah, keep envy and evil away from them. O Allah, always gather us upon goodness, obedience and sincere love. O Allah, grant us all a good end and the highest Paradise.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      orderIndex: 8,
    },
    {
      titleAr: "دعاء لمن أوصانا بالدعاء",
      titleEn: "Dua for Those Who Asked to be Remembered",
      arabicText: "اللَّهُمَّ يَا وَاسِعَ الرَّحْمَةِ، يَا كَرِيمَ الْعَطَاءِ، يَا مُجِيبَ الدَّعَوَاتِ، إِنَّ هُنَاكَ مَنْ أَوْصَانَا بِالدُّعَاءِ، فَاجْزِهِ عَنَّا خَيْرَ الْجَزَاءِ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.\n\nاللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ، وَبَارِكْ لَهُ فِي عُمْرِهِ وَصِحَّتِهِ وَرِزْقِهِ وَأَهْلِهِ.\n\nاللَّهُمَّ إِنْ كَانَ مَهْمُومًا فَفَرِّجْ هَمَّهُ، وَإِنْ كَانَ مَكْرُوبًا فَنَفِّسْ كُرْبَتَهُ، وَإِنْ كَانَ مَرِيضًا فَاشْفِهِ، وَإِنْ كَانَ مُحْتَاجًا فَأَغْنِهِ بِفَضْلِكَ.\n\nاللَّهُمَّ افْتَحْ لَهُ أَبْوَابَ الْخَيْرِ وَالتَّوْفِيقِ وَالسَّعَادَةِ مِنْ حَيْثُ لاَ يَحْتَسِبُ.\n\nاللَّهُمَّ ارْزُقْهُ رَاحَةً فِي الْقَلْبِ، وَسَكِينَةً فِي النَّفْسِ، وَبَرَكَةً فِي الْحَيَاةِ.\n\nاللَّهُمَّ حَقِّقْ لَهُ مَا يَتَمَنَّى إِنْ كَانَ فِيهِ خَيْرٌ لَهُ، وَاكْتُبْ لَهُ الْخَيْرَ حَيْثُ كَانَ ثُمَّ أَرْضِهِ بِهِ.\n\nاللَّهُمَّ اجْعَلْ لَهُ نَصِيبًا مِنْ كُلِّ دَعْوَةٍ صَالِحَةٍ تُرْفَعُ فِي هَذَا الْيَوْمِ الْمُبَارَكِ.\n\nاللَّهُمَّ لاَ تَدَعْ لَهُ ذَنْبًا إِلاَّ غَفَرْتَهُ، وَلاَ هَمًّا إِلاَّ فَرَّجْتَهُ، وَلاَ حَاجَةً مِنْ حَوَائِجِ الدُّنْيَا وَالآخِرَةِ إِلاَّ قَضَيْتَهَا لَهُ يَا أَرْحَمَ الرَّاحِمِينَ.\n\nاللَّهُمَّ اجْعَلْهُ مِنَ السُّعَدَاءِ فِي الدُّنْيَا وَالآخِرَةِ، وَمِنَ الْمَقْبُولِينَ عِنْدَكَ، وَمِنْ عُتَقَائِكَ مِنَ النَّارِ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم يا واسع الرحمة يا كريم العطاء، إن هناك من أوصانا بالدعاء فاجزه عنا خير الجزاء. اللهم اغفر له وارحمه وبارك له في عمره وصحته. اللهم إن كان مهمومًا ففرج همه وإن كان مريضًا فاشفه. اللهم افتح له أبواب الخير والتوفيق. اللهم اجعله من السعداء والمقبولين.",
      translationEn: "O Allah, O Most Merciful, O Generous Giver, there are those who asked us to pray for them, so reward them with the best reward. O Allah, forgive them, have mercy on them, and bless them in their life, health and family. O Allah, if they are worried, relieve their worry; if they are distressed, relieve their distress; if they are sick, cure them; if they are in need, enrich them. O Allah, make them among the happy and accepted ones, and among those freed from the Fire.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      orderIndex: 9,
    },
    {
      titleAr: "دعاء الفرج وتيسير الأمور",
      titleEn: "Dua for Relief and Ease of Affairs",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ عَدَدَ مَا خَلَقْتَ، وَلَكَ الْحَمْدُ مِلْءَ مَا خَلَقْتَ، وَلَكَ الْحَمْدُ عَدَدَ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ، وَلَكَ الْحَمْدُ حَتَّى تَرْضَى، وَلَكَ الْحَمْدُ إِذَا رَضِيتَ، وَلَكَ الْحَمْدُ بَعْدَ الرِّضَا.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ عَبْدِكَ وَرَسُولِكَ، وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ، صَلاَةً تَمْلَأُ السَّمَاوَاتِ وَالأَرْضَ وَمَا بَيْنَهُمَا.\n\nيَا رَبُّ، يَا كَرِيمُ، يَا لَطِيفُ، يَا قَرِيبُ، يَا مُجِيبَ الدَّعَوَاتِ، يَا مَنْ تَعْلَمُ مَا فِي الْقُلُوبِ، يَا مَنْ لاَ يَخْفَى عَلَيْهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ، نَسْأَلُكَ فِي هَذَا الْيَوْمِ الْمُبَارَكِ أَنْ تَجْعَلَ لَنَا مِنْ كُلِّ هَمٍّ فَرَجًا، وَمِنْ كُلِّ ضِيقٍ مَخْرَجًا، وَمِنْ كُلِّ بَلاَءٍ عَافِيَةً.\n\nاللَّهُمَّ إِنْ ضَاقَتْ بِنَا الدُّنْيَا فَأَنْتَ أَوْسَعُ، وَإِنْ ضَعُفَتْ قُلُوبُنَا فَأَنْتَ أَقْوَى، وَإِنِ انْقَطَعَتْ بِنَا الأَسْبَابُ فَبَابُكَ لاَ يُغْلَقُ.\n\nاللَّهُمَّ يَسِّرْ لَنَا أُمُورَنَا كُلَّهَا، مَا عَلِمْنَا مِنْهَا وَمَا لَمْ نَعْلَمْ، وَاكْتُبْ لَنَا الْخَيْرَ حَيْثُ كَانَ، ثُمَّ أَرْضِنَا بِهِ يَا رَبَّ الْعَالَمِينَ.\n\nاللَّهُمَّ افْتَحْ لَنَا أَبْوَابَ الرَّحْمَةِ وَالتَّوْفِيقِ وَالرِّزْقِ وَالْقَبُولِ، وَابْعَدْ عَنَّا أَبْوَابَ الشَّرِّ وَالْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْفَشَلِ.\n\nيَا رَبُّ إِنَّا نَسْأَلُكَ رَاحَةً لاَ تَزُولُ، وَفَرَحًا لاَ يَنْقَطِعُ، وَطَمْأَنِينَةً تَمْلَأُ قُلُوبَنَا.\n\nاللَّهُمَّ بَدِّلْ خَوْفَنَا أَمْنًا، وَحَزَنَنَا فَرَحًا، وَضَعْفَنَا قُوَّةً، وَكَسْرَنَا جَبْرًا جَمِيلًا يَلِيقُ بِكَرَمِكَ.\n\nاللَّهُمَّ اجْعَلْ لَنَا نَصِيبًا مِنْ كُلِّ خَيْرٍ تُنْزِلُهُ فِي هَذَا الْيَوْمِ الْمُبَارَكِ.\n\nاللَّهُمَّ ارْزُقْنَا يَقِينًا يَجْعَلُنَا نَعْلَمُ أَنَّ كُلَّ مَا كَتَبْتَهُ لَنَا خَيْرٌ، وَأَنَّ تَدْبِيرَكَ لَنَا أَفْضَلُ مِنْ تَدْبِيرِنَا لأَنْفُسِنَا.\n\nيَا رَبُّ لاَ تَحْمِلْنَا مَا لاَ طَاقَةَ لَنَا بِهِ، وَلاَ تَتْرُكْنَا لأَنْفُسِنَا طَرْفَةَ عَيْنٍ.\n\nاللَّهُمَّ اجْعَلْ أَقْدَارَنَا أَجْمَلَ مِمَّا نَتَمَنَّى، وَأَيَّامَنَا الْقَادِمَةَ مَلِيئَةً بِرَحْمَتِكَ وَلُطْفِكَ وَكَرَمِكَ.\n\nاللَّهُمَّ اجْعَلْ لَنَا دَعْوَةً لاَ تُرَدُّ، وَافْتَحْ لَنَا بَابًا إِلَى الْجَنَّةِ لاَ يُسَدُّ.\n\nاللَّهُمَّ إِنَّا نَسْتَوْدِعُكَ أَحْلاَمَنَا وَأُمْنِيَّاتِنَا وَمُسْتَقْبَلَنَا، فَاكْتُبْ لَنَا فِيهَا الْخَيْرَ وَالْبَرَكَةَ وَالتَّوْفِيقَ.\n\nاللَّهُمَّ ارْزُقْنَا سَعَادَةَ الدَّارَيْنِ، وَاجْعَلْنَا مِنْ عِبَادِكَ الرَّاضِينَ الْمَرْضِيِّينَ.\n\nرَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم لك الحمد عدد ما خلقت وملء ما خلقت، اللهم صل وسلم على سيدنا محمد. يا رب يا كريم يا مجيب الدعوات، نسألك أن تجعل لنا من كل هم فرجًا ومن كل ضيق مخرجًا. اللهم يسر لنا أمورنا واكتب لنا الخير. اللهم افتح لنا أبواب الرحمة والتوفيق والرزق. اللهم ارزقنا راحة وفرحًا وطمأنينة. اللهم بدّل خوفنا أمنًا وحزننا فرحًا. اللهم ارزقنا يقينًا بأن كل ما كتبته خير. ربنا تقبل منا وتب علينا.",
      translationEn: "O Allah, to You be praise as many as what You created, and filling what You created. O Allah, send prayers upon our master Muhammad. O Lord, O Generous, O Responder to prayers, we ask You to make for us from every worry a way out, from every hardship a relief. O Allah, ease all our affairs, write good for us. Open for us the doors of mercy, success, and provision. Grant us rest, joy, and tranquility. Replace our fear with safety, our sadness with joy. Grant us certainty that all You decree is good. Our Lord, accept from us and forgive us.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 10,
    },
    {
      titleAr: "دعاء راحة القلب والسكينة",
      titleEn: "Dua for Peace of Heart and Tranquility",
      arabicText: "اللَّهُمَّ يَا حَيُّ يَا قَيُّومُ، يَا ذَا الْجَلاَلِ وَالإِكْرَامِ، يَا وَاسِعَ الرَّحْمَةِ، يَا مَنْ بِيَدِهِ الْخَيْرُ كُلُّهُ، نَسْأَلُكَ أَنْ تَمْلَأَ قُلُوبَنَا نُورًا وَطَمْأَنِينَةً وَسَكِينَةً.\n\nاللَّهُمَّ لَكَ الْحَمْدُ عَلَى كُلِّ نِعْمَةٍ أَنْعَمْتَ بِهَا عَلَيْنَا، وَلَكَ الْحَمْدُ عَلَى كُلِّ قَضَاءٍ قَضَيْتَهُ لَنَا، وَلَكَ الْحَمْدُ فِي السَّرَّاءِ وَالضَّرَّاءِ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلِّمْ تَسْلِيمًا كَثِيرًا.\n\nيَا رَبُّ، إِنَّ قُلُوبَنَا مُتْعَبَةٌ وَأَنْتَ الرَّاحَةُ، وَإِنَّ أَرْوَاحَنَا عَطْشَى وَأَنْتَ السَّكِينَةُ، وَإِنَّ نُفُوسَنَا تَبْحَثُ عَنِ الأَمَانِ وَأَنْتَ السَّلاَمُ.\n\nاللَّهُمَّ أَنْزِلْ عَلَيْنَا بَرْدَ رَحْمَتِكَ، وَلُطْفَ عَفْوِكَ، وَجَمَالَ قُرْبِكَ.\n\nاللَّهُمَّ أَبْعِدْ عَنَّا الْقَلَقَ وَالتَّفْكِيرَ وَالْخَوْفَ وَالْحَزَنَ، وَارْزُقْنَا نَفْسًا مُطْمَئِنَّةً رَاضِيَةً بِقَضَائِكَ.\n\nاللَّهُمَّ اجْعَلْنَا مِمَّنْ إِذَا ضَاقَتْ بِهِمُ الدُّنْيَا لَجَؤُوا إِلَيْكَ فَوَسَّعَتْ عَلَيْهِمْ رَحْمَتُكَ.\n\nاللَّهُمَّ اجْعَلْ ذِكْرَكَ أَنِيسَ قُلُوبِنَا، وَالصَّلاَةَ رَاحَةَ أَرْوَاحِنَا، وَالْقُرْآنَ نُورَ حَيَاتِنَا.\n\nاللَّهُمَّ لاَ تَجْعَلْ فِي صُدُورِنَا حَزَنًا إِلاَّ أَذْهَبْتَهُ، وَلاَ خَوْفًا إِلاَّ آمَنْتَهُ، وَلاَ وَجَعًا إِلاَّ شَفَيْتَهُ.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ رَاحَةً تَمْحُو تَعَبَ السِّنِينَ، وَفَرَحًا يُنْسِينَا مُرَّ الأَيَّامِ.\n\nاللَّهُمَّ اجْعَلْنَا مِنَ الَّذِينَ إِذَا أَصَابَتْهُمْ مُصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، فَأَكْرَمْتَهُمْ بِالصَّبْرِ وَالرِّضَا وَالأَجْرِ الْعَظِيمِ.\n\nاللَّهُمَّ ارْزُقْنَا رَاحَةَ الْبَالِ، وَهُدُوءَ النَّفْسِ، وَسَلاَمَ الْقَلْبِ، وَصَفَاءَ الرُّوحِ.\n\nاللَّهُمَّ اجْعَلْ قُلُوبَنَا مُعَلَّقَةً بِكَ وَحْدَكَ، لاَ تَخَافُ إِلاَّ مِنْكَ، وَلاَ تَرْجُو إِلاَّ إِيَّاكَ.\n\nاللَّهُمَّ قَرِّبْنَا مِنْكَ قُرْبًا يَطْمَئِنُّ بِهِ الْقَلْبُ وَتَسْتَرِيحُ بِهِ الرُّوحُ.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ حَيَاةً هَادِئَةً، وَنَفْسًا مُطْمَئِنَّةً، وَدُعَاءً مُسْتَجَابًا، وَخَاتِمَةً حَسَنَةً.\n\nاللَّهُمَّ اجْعَلْ لَنَا نُورًا فِي قُلُوبِنَا، وَنُورًا فِي قُبُورِنَا، وَنُورًا يَوْمَ نَلْقَاكَ.\n\nاللَّهُمَّ اجْعَلِ الْجَنَّةَ دَارَنَا وَقَرَارَنَا، وَاجْعَلْنَا مِنْ عِبَادِكَ الصَّالِحِينَ الْمَقْبُولِينَ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم يا حي يا قيوم يا ذا الجلال والإكرام نسألك أن تملأ قلوبنا نورًا وطمأنينة. اللهم إن قلوبنا متعبة وأنت الراحة، وأرواحنا عطشى وأنت السكينة. اللهم أبعد عنا القلق والخوف والحزن وارزقنا نفسًا مطمئنة. اللهم اجعل ذكرك أنيس قلوبنا والصلاة راحة أرواحنا. اللهم ارزقنا راحة البال وهدوء النفس وسلام القلب.",
      translationEn: "O Allah, O Ever-Living, O Self-Sustaining, O Possessor of Majesty and Honor, we ask You to fill our hearts with light and tranquility. O Allah, our hearts are tired and You are the rest, our souls are thirsty and You are the peace. O Allah, remove from us anxiety, fear and sadness, grant us a contented soul. Make Your remembrance the comfort of our hearts and prayer the rest of our souls. Grant us peace of mind, calmness of soul, and serenity of heart.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 11,
    },
    {
      titleAr: "دعاء الرزق والبركة والنجاح",
      titleEn: "Dua for Provision, Blessings and Success",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلاَلِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ، الْحَمْدُ لِلَّهِ الَّذِي بِيَدِهِ خَزَائِنُ السَّمَاوَاتِ وَالأَرْضِ، الْحَمْدُ لِلَّهِ الرَّزَّاقِ الْكَرِيمِ الْوَهَّابِ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.\n\nيَا رَزَّاقُ يَا كَرِيمُ يَا فَتَّاحُ يَا عَلِيمُ، افْتَحْ لَنَا أَبْوَابَ رِزْقِكَ الْوَاسِعِ الْمُبَارَكِ، وَارْزُقْنَا مِنْ حَيْثُ لاَ نَحْتَسِبُ.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ رِزْقًا حَلاَلاً طَيِّبًا وَاسِعًا يُغْنِينَا عَنْ سُؤَالِ النَّاسِ.\n\nاللَّهُمَّ بَارِكْ لَنَا فِي أَرْزَاقِنَا وَأَعْمَالِنَا وَأَوْقَاتِنَا وَأَعْمَارِنَا.\n\nاللَّهُمَّ ارْزُقْنَا التَّوْفِيقَ فِي كُلِّ خَطْوَةٍ، وَالسَّدَادَ فِي كُلِّ قَرَارٍ، وَالنَّجَاحَ فِي كُلِّ أَمْرٍ فِيهِ خَيْرٌ لَنَا.\n\nيَا رَبُّ إِنَّا نَسْأَلُكَ رِزْقًا لاَ يَنْقَطِعُ، وَفَرَجًا لاَ يَنْتَهِي، وَنِعْمَةً تَدُومُ.\n\nاللَّهُمَّ اجْعَلْ أَيْدِيَنَا مُمْتَدَّةً بِالْخَيْرِ، وَقُلُوبَنَا مَمْتَلِئَةً بِالشُّكْرِ، وَأَلْسِنَتَنَا عَامِرَةً بِذِكْرِكَ.\n\nاللَّهُمَّ لاَ تَجْعَلِ الدُّنْيَا أَكْبَرَ هَمِّنَا، وَلَكِنِ اجْعَلْهَا فِي أَيْدِينَا لاَ فِي قُلُوبِنَا.\n\nاللَّهُمَّ ارْزُقْنَا الْقَنَاعَةَ وَالْبَرَكَةَ وَالرِّضَا، فَإِنَّ الرِّضَا أَعْظَمُ الْغِنَى.\n\nاللَّهُمَّ افْتَحْ لَنَا أَبْوَابَ النَّجَاحِ وَالتَّوْفِيقِ وَالْقَبُولِ بَيْنَ النَّاسِ.\n\nاللَّهُمَّ يَسِّرْ لَنَا كُلَّ عَسِيرٍ، وَقَرِّبْ لَنَا كُلَّ بَعِيدٍ، وَحَقِّقْ لَنَا مَا نَتَمَنَّى إِنْ كَانَ فِيهِ خَيْرٌ لَنَا.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ بَرَكَةً فِي الْمَالِ، وَبَرَكَةً فِي الصِّحَّةِ، وَبَرَكَةً فِي الْوَقْتِ، وَبَرَكَةً فِي الأَهْلِ وَالأَحْبَابِ.\n\nاللَّهُمَّ اجْعَلْنَا مِنَ الشَّاكِرِينَ لِنِعَمِكَ، الْحَامِدِينَ لِفَضْلِكَ، الذَّاكِرِينَ لَكَ كَثِيرًا.\n\nاللَّهُمَّ اكْفِنَا بِحَلاَلِكَ عَنْ حَرَامِكَ، وَأَغْنِنَا بِفَضْلِكَ عَمَّنْ سِوَاكَ.\n\nاللَّهُمَّ ارْزُقْنَا أَعْمَالاً صَالِحَةً تُقَرِّبُنَا إِلَيْكَ، وَأَرْزَاقًا مُبَارَكَةً تُعِينُنَا عَلَى طَاعَتِكَ.\n\nاللَّهُمَّ اجْعَلِ النَّجَاحَ حَلِيفَنَا، وَالتَّوْفِيقَ طَرِيقَنَا، وَالْجَنَّةَ غَايَتَنَا.\n\nاللَّهُمَّ ارْزُقْنَا حُسْنَ الْخَاتِمَةِ وَالْفِرْدَوْسَ الأَعْلَى بِغَيْرِ حِسَابٍ وَلاَ سَابِقِ عَذَابٍ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم لك الحمد كما ينبغي لجلال وجهك وعظيم سلطانك، الحمد لله الرزاق الكريم الوهاب. يا رزاق يا كريم يا فتاح افتح لنا أبواب رزقك الواسع. اللهم ارزقنا رزقًا حلالاً طيبًا وبارك لنا فيه. اللهم ارزقنا التوفيق والنجاح في كل أمر. اللهم اجعل النجاح حليفنا والتوفيق طريقنا والجنة غايتنا.",
      translationEn: "O Allah, to You be praise as befits the Majesty of Your Face and the Greatness of Your Power. Praise be to Allah, the Provider, the Generous, the Bestower. O Provider, O Generous, O Opener, open for us the doors of Your vast provision. Grant us lawful, good provision and bless us in it. Grant us success in every matter. Make success our companion, guidance our path, and Paradise our goal.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 12,
    },
    {
      titleAr: "دعاء القرب من الله والثبات",
      titleEn: "Dua for Closeness to Allah and Steadfastness",
      arabicText: "اللَّهُمَّ يَا نُورَ السَّمَاوَاتِ وَالأَرْضِ، يَا هَادِيَ الضَّالِّينَ، يَا أَرْحَمَ الرَّاحِمِينَ، نَسْأَلُكَ أَنْ تُقَرِّبَنَا إِلَيْكَ قُرْبًا لاَ نَبْعُدُ بَعْدَهُ أَبَدًا.\n\nاللَّهُمَّ لَكَ الْحَمْدُ أَنْ جَعَلْتَنَا مِنْ أَهْلِ الإِسْلاَمِ، وَلَكَ الْحَمْدُ أَنْ هَدَيْتَنَا بَعْدَ الضَّلاَلِ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى نَبِيِّنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلِّمْ.\n\nيَا رَبُّ، إِنَّا ضُعَفَاءُ فَقَوِّنَا بِطَاعَتِكَ، وَإِنَّا مُقَصِّرُونَ فَاغْفِرْ لَنَا، وَإِنَّا مُذْنِبُونَ فَارْحَمْنَا.\n\nاللَّهُمَّ ارْزُقْنَا حُبَّكَ، وَحُبَّ مَنْ يُحِبُّكَ، وَحُبَّ كُلِّ عَمَلٍ يُقَرِّبُنَا إِلَى حُبِّكَ.\n\nاللَّهُمَّ اجْعَلِ الصَّلاَةَ أَحَبَّ الأَشْيَاءِ إِلَى قُلُوبِنَا، وَالْقُرْآنَ رَبِيعَ صُدُورِنَا، وَذِكْرَكَ رَاحَةَ أَرْوَاحِنَا.\n\nاللَّهُمَّ لاَ تَجْعَلِ الدُّنْيَا تُلْهِينَا عَنْكَ، وَلاَ الشَّهَوَاتِ تُبْعِدُنَا عَنْ طَاعَتِكَ.\n\nاللَّهُمَّ ثَبِّتْنَا عَلَى دِينِكَ حَتَّى نَلْقَاكَ وَأَنْتَ رَاضٍ عَنَّا.\n\nاللَّهُمَّ اجْعَلْنَا مِنَ التَّوَّابِينَ، وَاجْعَلْنَا مِنَ الْمُتَطَهِّرِينَ، وَاجْعَلْنَا مِنْ عِبَادِكَ الصَّالِحِينَ.\n\nاللَّهُمَّ ارْزُقْنَا خُشُوعًا فِي الصَّلاَةِ، وَدَمْعَةً مِنْ خَشْيَتِكَ، وَقَلْبًا حَاضِرًا فِي ذِكْرِكَ.\n\nاللَّهُمَّ اجْعَلْنَا مِمَّنْ إِذَا أَذْنَبُوا اسْتَغْفَرُوا، وَإِذَا أَحْسَنُوا شَكَرُوا، وَإِذَا ابْتُلُوا صَبَرُوا.\n\nاللَّهُمَّ اجْعَلْ لَنَا نَصِيبًا مِنْ قِيَامِ اللَّيْلِ، وَمِنْ لَذَّةِ الدُّعَاءِ، وَمِنْ نُورِ الْقُرْآنِ.\n\nاللَّهُمَّ لاَ تَقْبِضْ أَرْوَاحَنَا إِلاَّ وَأَنْتَ رَاضٍ عَنَّا.\n\nاللَّهُمَّ اجْعَلْ خَيْرَ أَيَّامِنَا يَوْمَ نَلْقَاكَ، وَخَيْرَ أَعْمَالِنَا خَوَاتِيمَهَا.\n\nاللَّهُمَّ ارْزُقْنَا الْفِرْدَوْسَ الأَعْلَى بِلاَ حِسَابٍ وَلاَ سَابِقَةِ عَذَابٍ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم يا نور السماوات والأرض نسألك أن تقربنا إليك قربًا لا نبعد بعده أبدًا. اللهم ارزقنا حبك وحب من يحبك وحب كل عمل يقربنا إلى حبك. اللهم اجعل الصلاة أحب الأشياء إلينا والقرآن ربيع صدورنا. اللهم ثبتنا على دينك حتى نلقاك وأنت راض عنا. اللهم ارزقنا خشوعًا في الصلاة ودمعة من خشيتك. اللهم ارزقنا الفردوس الأعلى.",
      translationEn: "O Allah, Light of the heavens and earth, Guide of the lost, Most Merciful, we ask You to bring us close to You with a closeness after which we never stray. O Allah, grant us love for You, love for those who love You, and love for every deed that brings us closer to You. Make prayer the most beloved thing to us, the Quran the spring of our hearts. Make us steadfast on Your religion until we meet You while You are pleased with us. Grant us the highest Paradise.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 13,
    },
    {
      titleAr: "دعاء طويل جدًا ليوم عرفة",
      titleEn: "Very Long Comprehensive Dua for Arafah Day",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ حَتَّى تَرْضَى، وَلَكَ الْحَمْدُ إِذَا رَضِيتَ، وَلَكَ الْحَمْدُ بَعْدَ الرِّضَا، لَكَ الْحَمْدُ يَا رَبِّ عَلَى نِعَمِكَ الَّتِي لاَ تُعَدُّ وَلاَ تُحْصَى، لَكَ الْحَمْدُ أَنْ هَدَيْتَنَا لِلإِسْلاَمِ، وَلَكَ الْحَمْدُ أَنْ جَعَلْتَنَا مِنْ أُمَّةِ سَيِّدِنَا مُحَمَّدٍ صلى الله عليه وسلم، وَلَكَ الْحَمْدُ عَلَى مَا أَعْطَيْتَ وَمَا مَنَعْتَ، وَعَلَى مَا يَسَّرْتَ وَمَا أَخَّرْتَ، وَعَلَى كُلِّ حَالٍ يَا أَرْحَمَ الرَّاحِمِينَ.\n\nاللَّهُمَّ يَا حَيُّ يَا قَيُّومُ، يَا ذَا الْجَلاَلِ وَالإِكْرَامِ، يَا وَاسِعَ الرَّحْمَةِ، يَا عَظِيمَ الْفَضْلِ، يَا كَرِيمَ الْعَطَاءِ، يَا مَنْ بِيَدِهِ خَزَائِنُ السَّمَاوَاتِ وَالأَرْضِ، يَا مَنْ يَقُولُ لِلشَّيْءِ كُنْ فَيَكُونُ، يَا مَنْ لاَ يَعْجِزُهُ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ، نَسْأَلُكَ فِي هَذَا الْيَوْمِ الْعَظِيمِ الْمُبَارَكِ، يَوْمِ عَرَفَةَ، أَنْ تَتَجَلَّى عَلَيْنَا بِرَحْمَتِكَ وَعَفْوِكَ وَرِضَاكَ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا وَنَبِيِّنَا وَحَبِيبِنَا مُحَمَّدٍ صلى الله عليه وسلم، صَلاَةً دَائِمَةً كَامِلَةً مُبَارَكَةً، تَشْرَحُ بِهَا صُدُورَنَا، وَتُفَرِّجُ بِهَا هُمُومَنَا، وَتَغْفِرُ بِهَا ذُنُوبَنَا، وَتَرْفَعُ بِهَا دَرَجَاتِنَا، وَعَلَى آلِهِ الطَّيِّبِينَ الطَّاهِرِينَ وَصَحَابَتِهِ أَجْمَعِينَ وَمَنْ تَبِعَهُمْ بِإِحْسَانٍ إِلَى يَوْمِ الدِّينِ.\n\nاللَّهُمَّ إِنَّا وَقَفْنَا بِبَابِكَ، وَتَعَلَّقَتْ قُلُوبُنَا بِكَ، وَأَنْتَ تَعْلَمُ سِرَّنَا وَعَلاَنِيَتَنا، وَضَعْفَنَا وَفَقْرَنَا، وَحَاجَتَنَا إِلَيْكَ، يَا رَبِّ لاَ تَرُدَّنَا خَائِبِينَ، وَلاَ مِنْ رَحْمَتِكَ مَطْرُودِينَ، وَلاَ مِنْ عَطَائِكَ مَحْرُومِينَ.\n\nيَا رَبُّ، جِئْنَاكَ بِذُنُوبٍ كَثِيرَةٍ، وَخَطَايَا عَظِيمَةٍ، وَنُفُوسٍ مُثْقَلَةٍ بِالتَّقْصِيرِ، وَلَكِنْ جِئْنَاكَ أَيْضًا بِرَجَاءٍ عَظِيمٍ فِي رَحْمَتِكَ، وَحُسْنِ ظَنٍّ بِكَ، فَأَنْتَ أَهْلُ التَّقْوَى وَأَهْلُ الْمَغْفِرَةِ.\n\nاللَّهُمَّ اغْفِرْ لَنَا ذُنُوبَنَا كُلَّهَا، دِقَّهَا وَجِلَّهَا، أَوَّلَهَا وَآخِرَهَا، سِرَّهَا وَعَلاَنِيَتَهَا، مَا عَلِمْنَا مِنْهَا وَمَا لَمْ نَعْلَمْ، اللَّهُمَّ اغْفِرْ لَنَا الذُّنُوبَ الَّتِي تَهْتِكُ الْعِصَمَ، وَالذُّنُوبَ الَّتِي تُغَيِّرُ النِّعَمَ، وَالذُّنُوبَ الَّتِي تَمْنَعُ إِجَابَةَ الدُّعَاءِ، وَالذُّنُوبَ الَّتِي تُورِثُ النَّدَمَ وَالضِّيقَ وَالْحَزَنَ.\n\nاللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ ذَنْبٍ يَحْبِسُ رِزْقَنَا، أَوْ يُطْفِئُ نُورَ قُلُوبِنَا، أَوْ يُبْعِدُنَا عَنْكَ، أَوْ يَحْرِمُنَا لَذَّةَ طَاعَتِكَ.\n\nاللَّهُمَّ تُبْ عَلَيْنَا تَوْبَةً نَصُوحًا لاَ نَرْجِعُ بَعْدَهَا إِلَى مَعْصِيَةٍ أَبَدًا، اللَّهُمَّ طَهِّرْ قُلُوبَنَا، وَزَكِّ نُفُوسَنَا، وَاغْسِلْ خَطَايَانَا بِمَاءِ الرَّحْمَةِ وَالْمَغْفِرَةِ.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ قَلْبًا سَلِيمًا، وَلِسَانًا صَادِقًا، وَعَمَلاً صَالِحًا مُتَقَبَّلاً، وَيَقِينًا لاَ يَتَزَعْزَعُ، وَإِيمَانًا كَامِلاً، وَخُشُوعًا دَائِمًا، وَذِكْرًا كَثِيرًا.\n\nاللَّهُمَّ لاَ تَجْعَلِ الدُّنْيَا أَكْبَرَ هَمِّنَا، وَلاَ مَبْلَغَ عِلْمِنَا، وَلاَ إِلَى النَّارِ مَصِيرَنَا، وَاجْعَلِ الْجَنَّةَ هِيَ دَارَنَا وَقَرَارَنَا.\n\nيَا رَبُّ إِنْ كَانَتْ لَنَا ذُنُوبٌ تَمْنَعُ الْفَرَجَ فَاغْفِرْهَا، وَإِنْ كَانَتْ لَنَا خَطَايَا تَمْنَعُ الرِّزْقَ فَامْحُهَا، وَإِنْ كَانَتْ لَنَا عُيُوبٌ تَسْتَوْجِبُ الْعُقُوبَةَ فَاسْتُرْهَا يَا سَتَّارُ.\n\nاللَّهُمَّ ارْزُقْنَا قُرْبَكَ وَحُبَّكَ، وَاجْعَلْنَا مِمَّنْ إِذَا أَحْبَبْتَهُمْ نَادَيْتَ أَهْلَ السَّمَاءِ أَنَّكَ تُحِبُّهُمْ.\n\nاللَّهُمَّ ارْزُقْنَا لَذَّةَ النَّظَرِ إِلَى وَجْهِكَ الْكَرِيمِ، وَالشَّوْقَ إِلَى لِقَائِكَ، مِنْ غَيْرِ ضَرَّاءَ مُضِرَّةٍ وَلاَ فِتْنَةٍ مُضِلَّةٍ.\n\nاللَّهُمَّ اجْعَلِ الْقُرْآنَ الْعَظِيمَ رَبِيعَ قُلُوبِنَا، وَنُورَ صُدُورِنَا، وَجَلاَءَ أَحْزَانِنَا، وَذَهَابَ هُمُومِنَا وَغُمُومِنَا، اللَّهُمَّ ذَكِّرْنَا مِنْهُ مَا نَسِينَا، وَعَلِّمْنَا مِنْهُ مَا جَهِلْنَا، وَارْزُقْنَا تِلاَوَتَهُ آنَاءَ اللَّيْلِ وَأَطْرَافَ النَّهَارِ.\n\nاللَّهُمَّ اجْعَلْنَا مِنْ أَهْلِ الْقُرْآنِ الَّذِينَ هُمْ أَهْلُكَ وَخَاصَّتُكَ.\n\nاللَّهُمَّ يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قُلُوبَنَا عَلَى دِينِكَ، اللَّهُمَّ لاَ تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً إِنَّكَ أَنْتَ الْوَهَّابُ.\n\nاللَّهُمَّ ارْزُقْنَا حُسْنَ الْعِبَادَةِ، وَحُسْنَ الطَّاعَةِ، وَحُسْنَ الْقُرْبِ مِنْكَ، اللَّهُمَّ اجْعَلْنَا مِنَ الْمُحَافِظِينَ عَلَى الصَّلاَةِ، الْقَائِمِينَ بِاللَّيْلِ، الذَّاكِرِينَ لَكَ كَثِيرًا.\n\nاللَّهُمَّ أَعِنَّا عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ، اللَّهُمَّ اسْتُرْ عَوْرَاتِنَا، وَآمِنْ رَوْعَاتِنَا، وَاحْفَظْنَا مِنْ بَيْنِ أَيْدِينَا وَمِنْ خَلْفِنَا وَعَنْ أَيْمَانِنَا وَعَنْ شَمَائِلِنَا وَمِنْ فَوْقِنَا، وَنَعُوذُ بِعَظَمَتِكَ أَنْ نُغْتَالَ مِنْ تَحْتِنَا.\n\nاللَّهُمَّ احْفَظْنَا بِحِفْظِكَ الَّذِي لاَ يُرَامُ، وَاكْلَأْنَا بِعَيْنِكَ الَّتِي لاَ تَنَامُ، وَارْحَمْ ضَعْفَنَا وَقِلَّةَ حِيلَتِنَا.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ رِزْقًا وَاسِعًا حَلاَلاً طَيِّبًا مُبَارَكًا فِيهِ، اللَّهُمَّ افْتَحْ لَنَا أَبْوَابَ الْخَيْرِ وَالْبَرَكَةِ وَالتَّوْفِيقِ مِنْ حَيْثُ لاَ نَحْتَسِبُ.\n\nاللَّهُمَّ ارْزُقْنَا رِزْقًا لاَ يَجْعَلُنَا نَعْصِيكَ، وَغِنًى لاَ يُطْغِينَا، وَنِعْمَةً تُقَرِّبُنَا إِلَيْكَ.\n\nاللَّهُمَّ بَارِكْ لَنَا فِي أَعْمَارِنَا وَأَوْقَاتِنَا وَأَعْمَالِنَا وَأَهْلِنَا وَأَرْزَاقِنَا.\n\nاللَّهُمَّ اقْضِ دُيُونَ الْمَدِينِينَ، وَاشْفِ مَرْضَانَا وَمَرْضَى الْمُسْلِمِينَ، وَارْحَمْ مَوْتَانَا وَمَوْتَى الْمُسْلِمِينَ.\n\nاللَّهُمَّ مَنْ كَانَ مِنَّا مَهْمُومًا فَفَرِّجْ هَمَّهُ، وَمَنْ كَانَ مَكْرُوبًا فَنَفِّسْ كُرْبَتَهُ، وَمَنْ كَانَ مَرِيضًا فَاشْفِهِ، وَمَنْ كَانَ ضَالاًّ فَاهْدِهِ، وَمَنْ كَانَ مُحْتَاجًا فَأَغْنِهِ بِفَضْلِكَ.\n\nاللَّهُمَّ اجْعَلْ لَنَا مِنْ كُلِّ ضِيقٍ مَخْرَجًا، وَمِنْ كُلِّ هَمٍّ فَرَجًا، وَمِنْ كُلِّ بَلاَءٍ عَافِيَةً.\n\nاللَّهُمَّ ارْزُقْنَا رَاحَةً فِي الْقَلْبِ، وَطَمْأَنِينَةً فِي النَّفْسِ، وَسَكِينَةً فِي الرُّوحِ، وَانْشِرَاحًا فِي الصَّدْرِ.\n\nاللَّهُمَّ لاَ تَجْعَلْنَا نَحْمِلُ هَمَّ الْمُسْتَقْبَلِ وَأَنْتَ رَبُّ الْمُسْتَقْبَلِ، وَلاَ هَمَّ الرِّزْقِ وَأَنْتَ خَيْرُ الرَّازِقِينَ، وَلاَ هَمَّ الْخَلْقِ وَأَنْتَ حَسْبُنَا وَنِعْمَ الْوَكِيلُ.\n\nاللَّهُمَّ أَصْلِحْ لَنَا شَأْنَنَا كُلَّهُ، وَلاَ تَكِلْنَا إِلَى أَنْفُسِنَا طَرْفَةَ عَيْنٍ.\n\nاللَّهُمَّ إِنَّا نَسْأَلُكَ الْجَنَّةَ وَمَا قَرَّبَ إِلَيْهَا مِنْ قَوْلٍ وَعَمَلٍ، وَنَعُوذُ بِكَ مِنَ النَّارِ وَمَا قَرَّبَ إِلَيْهَا مِنْ قَوْلٍ وَعَمَلٍ.\n\nاللَّهُمَّ اجْعَلْ خَيْرَ أَعْمَالِنَا خَوَاتِيمَهَا، وَخَيْرَ أَيَّامِنَا يَوْمَ نَلْقَاكَ.\n\nاللَّهُمَّ ارْزُقْنَا حُسْنَ الْخَاتِمَةِ، وَاجْعَلْ آخِرَ كَلاَمِنَا مِنَ الدُّنْيَا شَهَادَةَ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ.\n\nاللَّهُمَّ ثَبِّتْنَا عِنْدَ الْمَوْتِ، وَثَبِّتْنَا فِي الْقَبْرِ عِنْدَ السُّؤَالِ، وَاجْعَلْ قُبُورَنَا رَوْضَةً مِنْ رِيَاضِ الْجَنَّةِ.\n\nاللَّهُمَّ اجْعَلْنَا يَوْمَ الْقِيَامَةِ مِنَ الآمِنِينَ الْمُطْمَئِنِّينَ، الَّذِينَ يَأْخُذُونَ كُتُبَهُمْ بِأَيْمَانِهِمْ، وَيَسِيرُونَ عَلَى الصِّرَاطِ كَالْبَرْقِ الْخَاطِفِ.\n\nاللَّهُمَّ اسْقِنَا مِنْ يَدِ نَبِيِّكَ مُحَمَّدٍ صلى الله عليه وسلم شَرْبَةً هَنِيئَةً لاَ نَظْمَأُ بَعْدَهَا أَبَدًا.\n\nاللَّهُمَّ اجْمَعْنَا بِنَبِيِّكَ فِي الْفِرْدَوْسِ الأَعْلَى، مَعَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَاءِ وَالصَّالِحِينَ، وَحَسُنَ أُولَئِكَ رَفِيقًا.\n\nاللَّهُمَّ انْصُرِ الإِسْلاَمَ وَالْمُسْلِمِينَ، وَأَعِزَّ دِينَكَ وَكِتَابَكَ وَسُنَّةَ نَبِيِّكَ وَعِبَادَكَ الصَّالِحِينَ.\n\nاللَّهُمَّ أَصْلِحْ أَحْوَالَ الْمُسْلِمِينَ فِي كُلِّ مَكَانٍ، وَارْفَعْ عَنْهُمُ الْبَلاَءَ وَالْفِتَنَ وَالْحُرُوبَ وَالْخَوْفَ وَالْجُوعَ.\n\nاللَّهُمَّ احْفَظْ أَهْلَنَا وَأَحْبَابَنَا وَمَنْ نُحِبُّ، وَاكْتُبْ لَهُمُ السَّعَادَةَ وَالطَّمَأْنِينَةَ وَالْبَرَكَةَ فِي الدُّنْيَا وَالآخِرَةِ.\n\nاللَّهُمَّ لاَ تَدَعْ لَنَا فِي هَذَا الْيَوْمِ الْمُبَارَكِ ذَنْبًا إِلاَّ غَفَرْتَهُ، وَلاَ هَمًّا إِلاَّ فَرَّجْتَهُ، وَلاَ كَرْبًا إِلاَّ نَفَّسْتَهُ، وَلاَ مَرِيضًا إِلاَّ شَفَيْتَهُ، وَلاَ مَيِّتًا إِلاَّ رَحِمْتَهُ، وَلاَ دُعَاءً إِلاَّ اسْتَجَبْتَهُ بِفَضْلِكَ يَا أَكْرَمَ الأَكْرَمِينَ.\n\nرَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً، وَفِي الآخِرَةِ حَسَنَةً، وَقِنَا عَذَابَ النَّارِ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى سَيِّدِنَا مُحَمَّدٍ، وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ، وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ.",
      translationAr: "اللهم لك الحمد حتى ترضى وبعد الرضا. اللهم يا حي يا قيوم نسألك في يوم عرفة أن تتجلى علينا برحمتك. اللهم صل وسلم على سيدنا محمد. اللهم إنا وقفنا ببابك فلا تردنا خائبين. اللهم اغفر لنا ذنوبنا كلها. اللهم تب علينا توبة نصوحًا. اللهم اجعل القرآن ربيع قلوبنا. اللهم ثبت قلوبنا على دينك. اللهم ارزقنا العفو والعافية. اللهم ارزقنا حسن الخاتمة. اللهم اجعلنا من أهل الجنة. ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة.",
      translationEn: "O Allah, to You be praise until You are pleased, and after You are pleased. O Allah, O Ever-Living, O Self-Sustaining, we ask You on this blessed day of Arafah to shower us with Your mercy, forgiveness and pleasure. O Allah, send blessings upon our master Muhammad. O Allah, we stand at Your door, do not turn us back empty-handed. O Allah, forgive us all our sins. O Allah, grant us sincere repentance. Make the Quran the spring of our hearts. Make our hearts firm upon Your religion. Grant us pardon and well-being. Grant us a good end. Make us among the people of Paradise. Our Lord, grant us good in this world and good in the Hereafter.",
      source: "دعاء مأثور — يوم عرفة",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: true,
      duaType: "long",
      orderIndex: 14,
    },
    {
      titleAr: "دعاء التوبة والمغفرة",
      titleEn: "Dua for Repentance and Forgiveness",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ كَمَا يَنْبَغِي لِجَلاَلِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ، اللَّهُمَّ أَنْتَ الْمَلِكُ لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ.\n\nاللَّهُمَّ يَا وَاسِعَ الرَّحْمَةِ، يَا عَظِيمَ الْمَنِّ، يَا كَرِيمَ الصَّفْحِ، يَا مَنْ لاَ يَعْجِزُهُ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ، أَسْأَلُكَ فِي هَذَا الْيَوْمِ الْعَظِيمِ، يَوْمِ عَرَفَةَ، أَنْ تَجْعَلَنِي مِنْ عُتَقَائِكَ مِنَ النَّارِ، وَأَنْ تَغْفِرَ لِي ذُنُوبِي كُلَّهَا، مَا عَلِمْتُ مِنْهَا وَمَا لَمْ أَعْلَمْ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ النَّبِيِّ الأُمِّيِّ، وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ، صَلاَةً تَفْتَحُ لَنَا بِهَا أَبْوَابَ الرَّحْمَةِ وَالْمَغْفِرَةِ وَالْقَبُولِ.\n\nاللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ وَارْحَمْنِي إِنَّكَ أَنْتَ الْغَفُورُ الرَّحِيمُ.\n\nيَا رَبُّ، إِنْ كَثُرَتْ ذُنُوبِي فَإِنَّ رَحْمَتَكَ أَوْسَعُ، وَإِنْ عَظُمَتْ خَطَايَايَ فَعَفْوُكَ أَعْظَمُ، اللَّهُمَّ لاَ تُؤَاخِذْنِي بِمَا فَعَلْتُ، وَلاَ بِمَا قَصَّرْتُ، وَلاَ بِمَا أَخْطَأْتُ.\n\nاللَّهُمَّ طَهِّرْ قَلْبِي مِنَ النِّفَاقِ، وَعَمَلِي مِنَ الرِّيَاءِ، وَلِسَانِي مِنَ الْكَذِبِ، وَعَيْنِي مِنَ الْخِيَانَةِ، فَإِنَّكَ تَعْلَمُ خَائِنَةَ الأَعْيُنِ وَمَا تُخْفِي الصُّدُورُ.\n\nاللَّهُمَّ ارْزُقْنِي تَوْبَةً نَصُوحًا قَبْلَ الْمَوْتِ، وَرَاحَةً عِنْدَ الْمَوْتِ، وَمَغْفِرَةً وَرَحْمَةً بَعْدَ الْمَوْتِ.\n\nاللَّهُمَّ إِنِّي أَسْأَلُكَ أَنْ تُبَدِّلَ سَيِّئَاتِي حَسَنَاتٍ، وَأَنْ تَسْتُرَ عُيُوبِي، وَأَنْ تَرْفَعَ قَدْرِي بِطَاعَتِكَ، وَأَنْ تَجْعَلَنِي مِنَ الْمَقْبُولِينَ فِي هَذَا الْيَوْمِ الْمُبَارَكِ.\n\nيَا رَبِّ لاَ تَرُدَّنِي خَائِبًا، وَلاَ تَجْعَلْ هَذَا الْيَوْمَ يَنْقَضِي إِلاَّ وَقَدْ كَتَبْتَنِي مِنَ السُّعَدَاءِ، وَغَفَرْتَ لِي وَلِوَالِدَيَّ وَأَهْلِي وَأَحْبَتِي.\n\nاللَّهُمَّ اجْعَلِ الْقُرْآنَ الْعَظِيمَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي وَجَلاَءَ حُزْنِي وَذَهَابَ هَمِّي.\n\nاللَّهُمَّ ارْزُقْنِي حُسْنَ الْخَاتِمَةِ، وَثَبِّتْنِي عِنْدَ السُّؤَالِ، وَاجْعَلْ قَبْرِي رَوْضَةً مِنْ رِيَاضِ الْجَنَّةِ.\n\nرَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ عَلَى نَبِيِّنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم لك الحمد كثيرًا، اللهم أنت الملك لا إله إلا أنت خلقتني وأنا عبدك. اللهم يا واسع الرحمة أسألك في يوم عرفة أن تجعلني من عتقائك من النار. اللهم إني ظلمت نفسي ظلمًا كثيرًا فاغفر لي. اللهم طهر قلبي من النفاق وعملي من الرياء. اللهم ارزقني توبة نصوحًا قبل الموت. اللهم بدّل سيئاتي حسنات. اللهم لا تردني خائبًا.",
      translationEn: "O Allah, to You be abundant praise. O Allah, You are the King, there is no god but You, You created me and I am Your servant. O Allah, O Most Merciful, I ask You on this day of Arafah to make me among those freed from the Fire. O Allah, I have wronged myself greatly, so forgive me. Purify my heart from hypocrisy and my deeds from show. Grant me sincere repentance before death. Replace my sins with good deeds. Do not turn me back empty-handed.",
      source: "دعاء مأثور — يوم عرفة",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 15,
    },
    {
      titleAr: "دعاء الرزق والتوفيق والفرج",
      titleEn: "Dua for Provision, Success and Relief",
      arabicText: "اللَّهُمَّ لَكَ الْحَمْدُ حَتَّى تَرْضَى، وَلَكَ الْحَمْدُ إِذَا رَضِيتَ، وَلَكَ الْحَمْدُ بَعْدَ الرِّضَا، اللَّهُمَّ أَنْتَ الْغَنِيُّ وَنَحْنُ الْفُقَرَاءُ إِلَيْكَ، وَأَنْتَ الْقَوِيُّ وَنَحْنُ الضُّعَفَاءُ إِلَيْكَ، وَأَنْتَ الْكَرِيمُ الَّذِي لاَ يَنْفَدُ عَطَاؤُهُ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.\n\nاللَّهُمَّ يَا فَتَّاحُ يَا رَزَّاقُ يَا كَرِيمُ، افْتَحْ لِي أَبْوَابَ رِزْقِكَ الْوَاسِعِ، وَيَسِّرْ لِيَ الْخَيْرَ حَيْثُ كَانَ، وَابْعِدْ عَنِّي كُلَّ ضِيقٍ وَعُسْرٍ وَهَمٍّ.\n\nاللَّهُمَّ إِنْ كَانَ رِزْقِي فِي السَّمَاءِ فَأَنْزِلْهُ، وَإِنْ كَانَ فِي الأَرْضِ فَأَخْرِجْهُ، وَإِنْ كَانَ بَعِيدًا فَقَرِّبْهُ، وَإِنْ كَانَ قَلِيلاً فَكَثِّرْهُ، وَإِنْ كَانَ كَثِيرًا فَبَارِكْ لِي فِيهِ.\n\nاللَّهُمَّ ارْزُقْنِي رِزْقًا حَلاَلاً طَيِّبًا مُبَارَكًا فِيهِ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ.\n\nيَا رَبِّ ارْزُقْنِي النَّجَاحَ وَالتَّوْفِيقَ وَالسَّدَادَ فِي حَيَاتِي، وَافْتَحْ لِي أَبْوَابَ الْخَيْرِ الَّتِي لاَ تَخْطُرُ لِي عَلَى بَالٍ.\n\nاللَّهُمَّ يَسِّرْ أَمْرِي، وَاشْرَحْ صَدْرِي، وَبَارِكْ لِي فِي وَقْتِي وَجَهْدِي وَعَمَلِي.\n\nاللَّهُمَّ أَبْعِدْ عَنِّي الْفَشَلَ وَالْعَجْزَ وَالْكَسَلَ، وَاجْعَلْنِي قَوِيًّا بِطَاعَتِكَ مُطْمَئِنًّا بِذِكْرِكَ.\n\nاللَّهُمَّ ارْزُقْنِي رَاحَةَ الْبَالِ، وَطَمْأَنِينَةَ الْقَلْبِ، وَسَكِينَةَ النَّفْسِ.\n\nاللَّهُمَّ فَرِّجْ هَمِّي، وَنَفِّسْ كَرْبِي، وَاقْضِ دَيْنِي، وَاشْفِ مَرْضِي، وَارْحَمْ ضَعْفِي.\n\nيَا رَبُّ إِنِّي أَسْأَلُكَ حَيَاةً هَنِيئَةً، وَنَفْسًا مُطْمَئِنَّةً، وَقَلْبًا رَاضِيًا، وَدُعَاءً مُسْتَجَابًا.\n\nاللَّهُمَّ اجْعَلِ الْقَادِمَ مِنْ حَيَاتِي خَيْرًا مِمَّا مَضَى، وَاكْتُبْ لِي مِنَ الْخَيْرِ فَوْقَ مَا أَتَمَنَّى.\n\nاللَّهُمَّ لاَ تَعْلُقْ قَلْبِي إِلاَّ بِكَ، وَلاَ تَجْعَلْ حَاجَتِي إِلاَّ إِلَيْكَ.\n\nرَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم لك الحمد حتى ترضى. اللهم يا فتاح يا رزاق يا كريم افتح لي أبواب رزقك. اللهم إن كان رزقي في السماء فأنزله وإن كان في الأرض فأخرجه. اللهم ارزقني رزقًا حلالاً طيبًا مباركًا فيه. اللهم يسر أمري واشرح صدري. اللهم فرج همي ونفس كربي. اللهم اجعل القادم خيرًا مما مضى.",
      translationEn: "O Allah, to You be praise until You are pleased. O Allah, O Opener, O Provider, O Generous, open for me the doors of Your provision. O Allah, if my provision is in the sky, send it down; if in the earth, bring it forth. Grant me lawful, good, blessed provision. Ease my affairs, expand my chest. Relieve my worries and distress. Make what is to come better than what has passed.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 16,
    },
    {
      titleAr: "دعاء شامل للدنيا والآخرة",
      titleEn: "Comprehensive Dua for This Life and the Hereafter",
      arabicText: "اللَّهُمَّ يَا رَحْمَنَ الدُّنْيَا وَالآخِرَةِ وَرَحِيمَهُمَا، يَا حَيُّ يَا قَيُّومُ، يَا ذَا الْجَلاَلِ وَالإِكْرَامِ، لَكَ الْحَمْدُ كُلُّهُ وَلَكَ الشُّكْرُ كُلُّهُ وَإِلَيْكَ يَرْجِعُ الأَمْرُ كُلُّهُ.\n\nاللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى نَبِيِّنَا مُحَمَّدٍ عَدَدَ مَا ذَكَرَهُ الذَّاكِرُونَ وَغَفَلَ عَنْ ذِكْرِهِ الْغَافِلُونَ.\n\nاللَّهُمَّ فِي يَوْمِ عَرَفَةَ الْمُبَارَكِ أَسْأَلُكَ رَحْمَةً مِنْ عِنْدِكَ تَهْدِي بِهَا قَلْبِي، وَتَجْمَعُ بِهَا أَمْرِي، وَتُصْلِحُ بِهَا شَأْنِي كُلَّهُ.\n\nاللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي، وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي، وَأَصْلِحْ لِي آخِرَتِي الَّتِي إِلَيْهَا مَعَادِي.\n\nاللَّهُمَّ اجْعَلِ الْحَيَاةَ زِيَادَةً لِي فِي كُلِّ خَيْرٍ، وَاجْعَلِ الْمَوْتَ رَاحَةً لِي مِنْ كُلِّ شَرٍّ.\n\nاللَّهُمَّ ارْزُقْنِي قَلْبًا خَاشِعًا، وَلِسَانًا ذَاكِرًا، وَعَمَلاً صَالِحًا مُتَقَبَّلاً.\n\nاللَّهُمَّ اجْعَلْنِي مِنْ عِبَادِكَ الصَّالِحِينَ، وَمِنْ أَوْلِيَائِكَ الْمُقَرَّبِينَ، وَمِنَ الَّذِينَ نَظَرْتَ إِلَيْهِمْ فَرَضِيتَ عَنْهُمْ.\n\nاللَّهُمَّ لاَ تَجْعَلْ فِي قَلْبِي حَزَنًا إِلاَّ فَرَّجْتَهُ، وَلاَ هَمًّا إِلاَّ أَزَلْتَهُ، وَلاَ دُعَاءً إِلاَّ أَجَبْتَهُ.\n\nاللَّهُمَّ ارْزُقْنِي حُبَّكَ، وَحُبَّ مَنْ يُحِبُّكَ، وَحُبَّ كُلِّ عَمَلٍ يُقَرِّبُنِي إِلَى حُبِّكَ.\n\nيَا رَبِّ اجْعَلْنِي بَارًّا بِوَالِدَيَّ، مُحْسِنًا لأَهْلِي، نَافِعًا لِلنَّاسِ، مُبَارَكًا أَيْنَمَا كُنْتُ.\n\nاللَّهُمَّ احْفَظْنِي مِنَ الْفِتَنِ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ.\n\nاللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي.\n\nاللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي وَاحْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي.\n\nاللَّهُمَّ اجْعَلْ آخِرَ كَلاَمِي مِنَ الدُّنْيَا شَهَادَةَ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ.\n\nاللَّهُمَّ اجْمَعْنَا فِي الْفِرْدَوْسِ الأَعْلَى مَعَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَاءِ وَالصَّالِحِينَ.\n\nرَبَّنَا لاَ تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً إِنَّكَ أَنْتَ الْوَهَّابُ.\n\nوَصَلَّى اللَّهُ وَسَلَّمَ وَبَارَكَ عَلَى نَبِيِّنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ.",
      translationAr: "اللهم يا رحمن الدنيا والآخرة أسألك رحمة تهدي بها قلبي وتصلح بها شأني. اللهم أصلح لي ديني ودنياي وآخرتي. اللهم ارزقني قلبًا خاشعًا ولسانًا ذاكرًا وعملًا متقبلًا. اللهم ارزقني حبك وحب من يحبك. اللهم اجعلني بارًا بوالدي محسنًا لأهلي. اللهم استر عوراتي وآمن روعاتي. اللهم اجمعنا في الفردوس الأعلى.",
      translationEn: "O Allah, Most Gracious of this world and the Hereafter, I ask You for mercy that guides my heart and rectifies my affairs. O Allah, rectify my religion, my worldly life, and my Hereafter. Grant me a humble heart, a remembering tongue, and accepted deeds. Grant me love for You and love for those who love You. Make me dutiful to my parents, kind to my family. Conceal my faults and secure me from fears. Gather us in the highest Paradise.",
      source: "دعاء مأثور",
      categoryName: "أدعية عرفات",
      mansakKey: "wuquf_arafah",
      isFeatured: false,
      duaType: "long",
      orderIndex: 17,
    },

    // ===== MUZDALIFAH & MINA =====
    {
      titleAr: "دعاء المبيت في مزدلفة",
      titleEn: "Dua at Muzdalifah",
      arabicText: "اللَّهُمَّ إِنَّ هَذَا الْمَشْعَرَ الْحَرَامَ حَرَّمْتَهُ، فَلاَ تُعَذِّبْنَا فِيهِ، وَاجْعَلْنَا مِنَ الَّذِينَ تَقَبَّلْتَ مِنْهُمْ، وَأَخْرِجْنَا مِنَ الذُّنُوبِ كَيَوْمِ وَلَدَتْنَا أُمَّهَاتُنَا",
      translationAr: "اللهم إن هذا المشعر الحرام حرّمته فلا تعذبنا فيه، واجعلنا من الذين تقبلت منهم، وأخرجنا من الذنوب كيوم ولدتنا أمهاتنا",
      translationEn: "O Allah, this is Al-Mash'ar Al-Haram which You have made sacred. Do not punish us in it. Make us among those from whom You accept, and purify us from sins as the day our mothers bore us.",
      source: "المأثور",
      categoryName: "أدعية مزدلفة ومنى",
      mansakKey: "muzdalifah",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء الوقوف في المشعر الحرام",
      titleEn: "Dua at Al-Mash'ar Al-Haram",
      arabicText: "اللَّهُمَّ كَمَا وَقَفْتَنَا فِيهِ وَأَرَيْتَنَا إِيَّاهُ فَوَفِّقْنَا لِذِكْرِكَ كَمَا هَدَيْتَنَا، وَاغْفِرْ لَنَا وَارْحَمْنَا كَمَا وَعَدْتَنَا بِقَوْلِكَ وَقَوْلُكَ الْحَقُّ",
      translationAr: "اللهم كما وقفتنا فيه وأريتنا إياه فوفقنا لذكرك كما هديتنا، واغفر لنا وارحمنا كما وعدتنا بقولك وقولك الحق",
      translationEn: "O Allah, just as You made us stand here and showed it to us, grant us success in remembering You as You guided us, and forgive and have mercy on us as You promised, and Your word is truth.",
      source: "المأثور",
      categoryName: "أدعية مزدلفة ومنى",
      mansakKey: "muzdalifah",
      isFeatured: false,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء أيام التشريق في منى",
      titleEn: "Dua during Days of Tashreeq at Mina",
      arabicText: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      translationAr: "ربنا أعطنا في الدنيا خيراً وفي الآخرة خيراً وقنا عذاب النار — وهو أكثر ما كان يقوله النبي ﷺ في أيام منى",
      translationEn: "Our Lord, grant us good in this world and good in the Hereafter, and protect us from the punishment of the Fire — the most frequent dua of the Prophet ﷺ in the days of Mina.",
      source: "البخاري ومسلم — الآية: البقرة ٢٠١",
      categoryName: "أدعية مزدلفة ومنى",
      mansakKey: "muzdalifah",
      isFeatured: true,
      orderIndex: 3,
    },

    // ===== JAMARAT DUAS =====
    {
      titleAr: "دعاء رمي الجمرة الأولى",
      titleEn: "Dua when throwing the First Jamrah",
      arabicText: "بِسْمِ اللَّهِ، اللَّهُ أَكْبَرُ، رَغْمًا لِلشَّيْطَانِ وَحِزْبِهِ",
      translationAr: "بسم الله، الله أكبر — يُقال مع كل حصاة — رغماً للشيطان وحزبه",
      translationEn: "In the name of Allah, Allah is the Greatest — said with each pebble — in humiliation of Satan and his party.",
      source: "صحيح البخاري",
      categoryName: "أدعية الجمرات",
      mansakKey: "rami_aqaba",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء رمي جمرة العقبة",
      titleEn: "Dua when throwing Jamrat Al-Aqabah",
      arabicText: "بِسْمِ اللَّهِ، اللَّهُ أَكْبَرُ، رَغْمًا لِلشَّيْطَانِ وَحِزْبِهِ، اللَّهُمَّ اجْعَلْهُ حَجًّا مَبْرُورًا وَسَعْيًا مَشْكُورًا وَذَنْبًا مَغْفُورًا",
      translationAr: "بسم الله، الله أكبر، إهانةً للشيطان وجنوده. اللهم اجعله حجاً مبروراً وسعياً مشكوراً وذنباً مغفوراً",
      translationEn: "In the name of Allah, Allah is the Greatest, in humiliation of Satan and his party. O Allah, make it an accepted Hajj, a thanked effort, and a forgiven sin.",
      source: "ابن ماجه",
      categoryName: "أدعية الجمرات",
      mansakKey: "rami_aqaba",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء بعد رمي الجمرة الصغرى والوسطى",
      titleEn: "Dua After the Small and Middle Jamrah",
      arabicText: "اللَّهُمَّ اجْعَلْهُ حَجًّا مَبْرُورًا وَذَنْبًا مَغْفُورًا، اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
      translationAr: "اللهم اجعله حجاً مبروراً وذنباً مغفوراً. اللهم أعني على ذكرك وشكرك وحسن عبادتك",
      translationEn: "O Allah, make it an accepted Hajj and a forgiven sin. O Allah, help me to remember You, thank You, and worship You well.",
      source: "صحيح البخاري",
      categoryName: "أدعية الجمرات",
      mansakKey: "rami_aqaba",
      isFeatured: false,
      orderIndex: 3,
    },

    // ===== MADINAH DUAS =====
    {
      titleAr: "دعاء دخول المسجد النبوي",
      titleEn: "Dua for Entering the Prophet's Mosque",
      arabicText: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ، اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَسَلِّمْ",
      translationAr: "اللهم افتح لي أبواب رحمتك. اللهم صل على محمد وسلم",
      translationEn: "O Allah, open for me the gates of Your mercy. O Allah, send prayers and peace upon Muhammad.",
      source: "مسلم",
      categoryName: "أدعية المدينة المنورة",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "السلام على النبي ﷺ",
      titleEn: "Salutation upon the Prophet ﷺ",
      arabicText: "السَّلاَمُ عَلَيْكَ يَا رَسُولَ اللَّهِ، السَّلاَمُ عَلَيْكَ يَا نَبِيَّ اللَّهِ، السَّلاَمُ عَلَيْكَ يَا حَبِيبَ اللَّهِ، أَشْهَدُ أَنَّكَ قَدْ بَلَّغْتَ الرِّسَالَةَ وَأَدَّيْتَ الأَمَانَةَ وَنَصَحْتَ الأُمَّةَ",
      translationAr: "السلام عليك يا رسول الله، السلام عليك يا نبي الله، السلام عليك يا حبيب الله. أشهد أنك بلّغت الرسالة وأدّيت الأمانة ونصحت الأمة",
      translationEn: "Peace be upon you, O Messenger of Allah. Peace be upon you, O Prophet of Allah. Peace be upon you, O beloved of Allah. I bear witness that you conveyed the message, fulfilled the trust and advised the nation.",
      source: "السنة النبوية",
      categoryName: "أدعية المدينة المنورة",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء زيارة المدينة المنورة",
      titleEn: "Dua for Visiting Madinah",
      arabicText: "اللَّهُمَّ هَذَا حَرَمُ نَبِيِّكَ، فَاجْعَلْهُ لِي وِقَايَةً مِنَ النَّارِ، وَأَمَانًا مِنَ الْعَذَابِ، وَسُوءِ الْحِسَابِ",
      translationAr: "اللهم هذا حرم نبيك فاجعله لي وقايةً من النار وأماناً من العذاب وسوء الحساب",
      translationEn: "O Allah, this is the sanctuary of Your Prophet, so make it a protection for me from the Fire, security from punishment, and from a bad reckoning.",
      source: "المأثور",
      categoryName: "أدعية المدينة المنورة",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "الصلاة على النبي ﷺ عند قبره",
      titleEn: "Salah upon the Prophet at His Grave",
      arabicText: "اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ صَلاَةً تَحِلُّ بِهَا عُقْدَتِي، وَتُفَرِّجُ بِهَا كُرْبَتِي، وَتَمْحُو بِهَا خَطِيئَتِي، وَتَقْضِي بِهَا حَاجَتِي",
      translationAr: "اللهم صل على سيدنا محمد صلاةً تحل بها عقدتي وتفرج بها كربتي وتمحو بها خطيئتي وتقضي بها حاجتي",
      translationEn: "O Allah, send prayers upon our master Muhammad, prayers that untie my knot, relieve my distress, erase my sin, and fulfill my need.",
      source: "المأثور",
      categoryName: "أدعية المدينة المنورة",
      isFeatured: false,
      orderIndex: 4,
    },

    // ===== MORNING & EVENING =====
    {
      titleAr: "أصبحنا وأصبح الملك لله",
      titleEn: "Morning Remembrance",
      arabicText: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ",
      translationAr: "أصبحنا وأصبح الملك لله والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. ربي أسألك خير ما في هذا اليوم وخير ما بعده",
      translationEn: "We have reached the morning and at this very time all sovereignty belongs to Allah. Praise be to Allah. None has the right to be worshipped except Allah, alone, without partner. My Lord, I ask You for the good of this day and the good of what follows it.",
      source: "مسلم",
      categoryName: "أذكار الصباح والمساء",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "يا حي يا قيوم",
      titleEn: "Ya Hayyu Ya Qayyum",
      arabicText: "يَا حَيُّ يَا قَيُّومُ، بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ",
      translationAr: "يا من لا يزول وجوده، يا من قائم على كل شيء، بكرمك ورحمتك أستعين، أصلح لي كل أموري ولا تتركني لنفسي لحظة واحدة",
      translationEn: "O Ever Living, O Self-Sustaining Supporter of all, by Your mercy I seek assistance. Rectify for me all of my affairs and do not leave me to myself, even for the blink of an eye.",
      source: "الحاكم — صحيح",
      categoryName: "أذكار الصباح والمساء",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "سيد الاستغفار",
      titleEn: "Master of Seeking Forgiveness",
      arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ",
      translationAr: "اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت. أعوذ بك من شر ما صنعت، وأعترف لك بنعمتك عليّ، وأعترف بذنبي، فاغفر لي، فإنه لا يغفر الذنوب إلا أنت",
      translationEn: "O Allah, You are my Lord, there is no god but You. You created me and I am Your servant. I uphold Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your blessings upon me and acknowledge my sins, so forgive me, for none forgives sins except You.",
      source: "البخاري — من قالها صباحاً موقناً ومات في يومه دخل الجنة",
      categoryName: "أذكار الصباح والمساء",
      isFeatured: true,
      orderIndex: 3,
    },
    {
      titleAr: "أعوذ بكلمات الله التامات",
      titleEn: "Refuge with Allah's Perfect Words",
      arabicText: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
      translationAr: "أتحصن بكلمات الله الكاملة من شر كل ما خلق الله",
      translationEn: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
      source: "مسلم — ثلاث مرات في المساء",
      categoryName: "أذكار الصباح والمساء",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "بسم الله الذي لا يضر",
      titleEn: "In Allah's Name who causes no harm",
      arabicText: "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
      translationAr: "بسم الله الذي بذكر اسمه لا يؤذي شيء في الأرض ولا في السماء، وهو السميع العليم",
      translationEn: "In the name of Allah with Whose name nothing can cause harm in the earth or the heavens, and He is the All-Hearing, All-Knowing.",
      source: "أبو داود والترمذي — ثلاث مرات صباحاً ومساءً",
      categoryName: "أذكار الصباح والمساء",
      isFeatured: false,
      orderIndex: 5,
    },
    {
      titleAr: "رضيت بالله رباً",
      titleEn: "Contentment with Allah",
      arabicText: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ صلى الله عليه وسلم نَبِيًّا",
      translationAr: "رضيت بالله رباً ومعبوداً، وبالإسلام ديناً ومنهجاً، وبمحمد ﷺ نبياً ورسولاً",
      translationEn: "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (peace be upon him) as my Prophet.",
      source: "أبو داود — ثلاث مرات في الصباح والمساء",
      categoryName: "أذكار الصباح والمساء",
      isFeatured: false,
      orderIndex: 6,
    },

    // ===== PRAYER DUAS =====
    {
      titleAr: "دعاء الاستفتاح",
      titleEn: "Opening Supplication",
      arabicText: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلاَ إِلَهَ غَيْرُكَ",
      translationAr: "سبحانك اللهم وبحمدك، تبارك اسمك وتعالت عظمتك، ولا إله غيرك",
      translationEn: "Glory and praise be to You, O Allah. Blessed be Your name, exalted be Your majesty, and there is no god but You.",
      source: "أبو داود والترمذي",
      categoryName: "أدعية الصلاة",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء الركوع",
      titleEn: "Dua in Ruku",
      arabicText: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
      translationAr: "سبحان ربي العظيم",
      translationEn: "Glory be to my Lord, the Magnificent.",
      source: "أبو داود — ثلاث مرات في الركوع",
      categoryName: "أدعية الصلاة",
      isFeatured: false,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء السجود",
      titleEn: "Dua in Sujud",
      arabicText: "سُبْحَانَ رَبِّيَ الأَعْلَى",
      translationAr: "سبحان ربي الأعلى",
      translationEn: "Glory be to my Lord, the Most High.",
      source: "أبو داود — ثلاث مرات في السجود",
      categoryName: "أدعية الصلاة",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "التشهد",
      titleEn: "Tashahhud",
      arabicText: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلاَمُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلاَمُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
      translationAr: "التحيات والعبادات والطيبات لله، السلام عليك أيها النبي ورحمة الله وبركاته، السلام علينا وعلى عباد الله الصالحين. أشهد أن لا إله إلا الله وأشهد أن محمداً عبده ورسوله",
      translationEn: "All greetings of humility are for Allah, and all prayers and goodness. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous slaves of Allah. I bear witness that none has the right to be worshipped except Allah, and I bear witness that Muhammad is His slave and Messenger.",
      source: "البخاري ومسلم",
      categoryName: "أدعية الصلاة",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "الصلاة الإبراهيمية",
      titleEn: "Ibrahimiyyah Prayer upon the Prophet",
      arabicText: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
      translationAr: "اللهم صلّ على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد",
      translationEn: "O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrahim and the family of Ibrahim; You are indeed Worthy of Praise, Full of Glory.",
      source: "البخاري ومسلم",
      categoryName: "أدعية الصلاة",
      isFeatured: false,
      orderIndex: 5,
    },
    {
      titleAr: "دعاء القنوت",
      titleEn: "Qunut Dua",
      arabicText: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ، فَإِنَّكَ تَقْضِي وَلاَ يُقْضَى عَلَيْكَ، إِنَّهُ لاَ يَذِلُّ مَنْ وَالَيْتَ، تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ",
      translationAr: "اللهم اهدني فيمن هديت وعافني فيمن عافيت وتولني فيمن توليت وبارك لي فيما أعطيت وقني شر ما قضيت، فإنك تقضي ولا يُقضى عليك، إنه لا يذل من واليت تباركت ربنا وتعاليت",
      translationEn: "O Allah, guide me among those You have guided, grant me well-being among those You have granted well-being, take me as an ally among those You have taken as allies, bless me in what You have given, and protect me from the evil of what You have decreed.",
      source: "أبو داود والترمذي والنسائي",
      categoryName: "أدعية الصلاة",
      isFeatured: false,
      orderIndex: 6,
    },

    // ===== GENERAL DUAS =====
    {
      titleAr: "دعاء الكرب",
      titleEn: "Dua of Distress",
      arabicText: "لاَ إِلَهَ إِلاَّ اللَّهُ الْعَظِيمُ الْحَلِيمُ، لاَ إِلَهَ إِلاَّ اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لاَ إِلَهَ إِلاَّ اللَّهُ رَبُّ السَّمَوَاتِ وَرَبُّ الأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",
      translationAr: "لا إله إلا الله العظيم الحليم، لا إله إلا الله رب العرش العظيم، لا إله إلا الله رب السماوات ورب الأرض ورب العرش الكريم",
      translationEn: "There is no god but Allah, the Mighty, the Forbearing. There is no god but Allah, Lord of the Mighty Throne. There is no god but Allah, Lord of the heavens, Lord of the earth, and Lord of the Noble Throne.",
      source: "البخاري ومسلم",
      categoryName: "أدعية جامعة",
      isFeatured: true,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء يونس عليه السلام",
      titleEn: "Dua of Yunus (AS)",
      arabicText: "لاَ إِلَهَ إِلاَّ أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
      translationAr: "لا إله غيرك، سبحانك وتنزيهاً لك، إني كنت ظالماً لنفسي",
      translationEn: "There is no god but You. Glory be to You. Verily, I was among the wrongdoers.",
      source: "القرآن الكريم — الأنبياء: ٨٧ — ما دعا بها مكروب إلا فرّج الله عنه",
      categoryName: "أدعية جامعة",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "ربنا آتنا في الدنيا حسنة",
      titleEn: "Dua for Good in Both Worlds",
      arabicText: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      translationAr: "ربنا أعطنا في الدنيا خيراً وفي الآخرة خيراً وقنا عذاب النار",
      translationEn: "Our Lord, grant us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
      source: "البقرة: ٢٠١ — أكثر ما كان النبي ﷺ يدعو به",
      categoryName: "أدعية جامعة",
      isFeatured: true,
      orderIndex: 3,
    },
    {
      titleAr: "اللهم إني أسألك العفو والعافية",
      titleEn: "Dua for Pardon and Well-Being",
      arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ",
      translationAr: "اللهم إني أسألك العفو والعافية في الدنيا والآخرة",
      translationEn: "O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
      source: "ابن ماجه — صحيح",
      categoryName: "أدعية جامعة",
      isFeatured: false,
      orderIndex: 4,
    },
    {
      titleAr: "اللهم أصلح لي ديني",
      titleEn: "Dua for Complete Rectification",
      arabicText: "اللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي، وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي، وَأَصْلِحْ لِي آخِرَتِي الَّتِي فِيهَا مَعَادِي، وَاجْعَلِ الْحَيَاةَ زِيَادَةً لِي فِي كُلِّ خَيْرٍ، وَاجْعَلِ الْمَوْتَ رَاحَةً لِي مِنْ كُلِّ شَرٍّ",
      translationAr: "اللهم أصلح لي ديني الذي هو عصمة أمري، وأصلح لي دنياي التي فيها معاشي، وأصلح لي آخرتي التي فيها معادي، واجعل الحياة زيادةً لي في كل خير، واجعل الموت راحةً لي من كل شر",
      translationEn: "O Allah, rectify for me my religion which is the safeguard of my affairs; rectify for me my worldly affairs in which is my livelihood; rectify for me my Hereafter which is my final return; make life for me an increase in every good, and make death a rest for me from every evil.",
      source: "مسلم",
      categoryName: "أدعية جامعة",
      isFeatured: false,
      orderIndex: 5,
    },

    // ===== EMERGENCY & DISTRESS =====
    {
      titleAr: "حسبنا الله ونعم الوكيل",
      titleEn: "Allah is Sufficient for Us",
      arabicText: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
      translationAr: "يكفينا الله ونعم المتولي لأمورنا — قالها إبراهيم عليه السلام حين أُلقي في النار",
      translationEn: "Allah is sufficient for us, and He is the best Disposer of affairs — said by Ibrahim (AS) when cast into the fire.",
      source: "البخاري — آل عمران: ١٧٣",
      categoryName: "أدعية الطوارئ والضيق",
      isFeatured: true,
      orderIndex: 1,
    },
    {
      titleAr: "اللهم لا سهل إلا ما جعلته سهلاً",
      titleEn: "Dua for Ease",
      arabicText: "اللَّهُمَّ لاَ سَهْلَ إِلاَّ مَا جَعَلْتَهُ سَهْلاً، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلاً",
      translationAr: "اللهم لا سهل إلا ما جعلته سهلاً، وأنت تجعل الحزن إذا شئت سهلاً",
      translationEn: "O Allah, there is no ease except what You make easy, and You make difficulty, if You wish, easy.",
      source: "ابن حبان — صحيح",
      categoryName: "أدعية الطوارئ والضيق",
      isFeatured: false,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء الهم والحزن",
      titleEn: "Dua for Worry and Sorrow",
      arabicText: "اللَّهُمَّ إِنِّي عَبْدُكَ وَابْنُ عَبْدِكَ وَابْنُ أَمَتِكَ، نَاصِيَتِي بِيَدِكَ، مَاضٍ فِيَّ حُكْمُكَ، عَدْلٌ فِيَّ قَضَاؤُكَ، أَسْأَلُكَ بِكُلِّ اسْمٍ هُوَ لَكَ سَمَّيْتَ بِهِ نَفْسَكَ أَوْ عَلَّمْتَهُ أَحَدًا مِنْ خَلْقِكَ أَوْ أَنْزَلْتَهُ فِي كِتَابِكَ أَوِ اسْتَأْثَرْتَ بِهِ فِي عِلْمِ الْغَيْبِ عِنْدَكَ، أَنْ تَجْعَلَ الْقُرْآنَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي وَجَلاَءَ حُزْنِي وَذَهَابَ هَمِّي",
      translationAr: "اللهم إني عبدك وابن عبدك وابن أمتك، ناصيتي بيدك، ماضٍ فيّ حكمك، عدل فيّ قضاؤك. أسألك بكل اسم هو لك سميت به نفسك أن تجعل القرآن ربيع قلبي ونور صدري وجلاء حزني وذهاب همي",
      translationEn: "O Allah, I am Your servant, son of Your servant, son of Your female servant. My forelock is in Your Hand. Your command over me is perpetually executed and Your decree over me is just. I ask You by every name that belongs to You which You named Yourself, to make the Quran the spring of my heart, the light of my chest, and the departure of my sorrow.",
      source: "أحمد — من قالها أذهب الله همه وحزنه وأبدله مكانه فرجاً",
      categoryName: "أدعية الطوارئ والضيق",
      isFeatured: false,
      duaType: "long",
      orderIndex: 3,
    },
    {
      titleAr: "لا إله إلا أنت سبحانك",
      titleEn: "Dua of Yunus for Relief",
      arabicText: "لاَ إِلَهَ إِلاَّ أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
      translationAr: "لا إله غيرك، سبحانك وتنزيهاً لك، إني كنت ظالماً لنفسي",
      translationEn: "There is no god but You, Glory be to You, indeed I was among the wrongdoers.",
      source: "الأنبياء: ٨٧ — ما دعا مكروب إلا فرّج الله عنه",
      categoryName: "أدعية الطوارئ والضيق",
      isFeatured: false,
      orderIndex: 4,
    },

    // ===== TRAVEL DUAS =====
    {
      titleAr: "دعاء مغادرة المنزل",
      titleEn: "Dua for Leaving Home",
      arabicText: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ",
      translationAr: "بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله",
      translationEn: "In the name of Allah, I place my trust in Allah, and there is no might or power except with Allah.",
      source: "أبو داود والترمذي",
      categoryName: "أدعية السفر",
      isFeatured: false,
      orderIndex: 1,
    },
    {
      titleAr: "دعاء ركوب السيارة أو الطائرة",
      titleEn: "Dua when Boarding a Vehicle",
      arabicText: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ، اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى",
      translationAr: "سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون. اللهم إنا نسألك في سفرنا هذا البر والتقوى ومن العمل ما ترضى",
      translationEn: "Glory be to Him who has subjected this to us, and we could not have done it ourselves. And indeed, to our Lord we will return. O Allah, we ask You for righteousness and piety on this journey, and deeds that please You.",
      source: "مسلم — الزخرف: ١٣-١٤",
      categoryName: "أدعية السفر",
      isFeatured: true,
      orderIndex: 2,
    },
    {
      titleAr: "دعاء العودة من السفر",
      titleEn: "Dua upon Returning from Travel",
      arabicText: "آيِبُونَ، تَائِبُونَ، عَابِدُونَ، لِرَبِّنَا حَامِدُونَ",
      translationAr: "راجعون إلى ربنا، تائبون إليه، عابدون له، لربنا حامدون ومُثنون عليه",
      translationEn: "We are returning, repenting, worshipping, and praising our Lord.",
      source: "البخاري ومسلم",
      categoryName: "أدعية السفر",
      isFeatured: false,
      orderIndex: 3,
    },
    {
      titleAr: "دعاء نزول المنزل في السفر",
      titleEn: "Dua when Stopping at a Place",
      arabicText: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
      translationAr: "أتحصن بكلمات الله الكاملة من شر كل ما خلق — يُقال عند النزول في أي مكان",
      translationEn: "I seek refuge in the perfect words of Allah from the evil of what He has created — said when stopping at any place.",
      source: "مسلم",
      categoryName: "أدعية السفر",
      isFeatured: false,
      orderIndex: 4,
    },

    // ===== FULL LONG DUAS =====
    {
      titleAr: "دعاء ختم طواف الوداع الكامل",
      titleEn: "Full Farewell Tawaf Completion Dua",
      arabicText: "اللَّهُمَّ إِنَّ الْبَيْتَ بَيْتُكَ، وَالْحَرَمَ حَرَمُكَ، وَالأَمْنَ أَمْنُكَ، وَهَذَا مَقَامُ الْعَائِذِ بِكَ مِنَ النَّارِ، اللَّهُمَّ إِنَّكَ دَعَوْتَ إِلَى حَجِّ بَيْتِكَ الْحَرَامِ وَقَدْ جِئْنَا سَامِعِينَ مُطِيعِينَ، فَاغْفِرْ لَنَا وَارْحَمْنَا كَمَا أَمَرْتَنَا، اللَّهُمَّ تَقَبَّلْ مِنَّا وَارْفَعْ دَرَجَاتِنَا وَأَلْحِقْنَا بِالصَّالِحِينَ",
      translationAr: "اللهم إن البيت بيتك والحرم حرمك والأمن أمنك وهذا مقام العائذ بك من النار. اللهم إنك دعوت إلى حج بيتك الحرام وقد جئنا سامعين مطيعين، فاغفر لنا وارحمنا كما أمرتنا. اللهم تقبل منا وارفع درجاتنا وألحقنا بالصالحين",
      translationEn: "O Allah, the House is Your House, the sanctuary is Your sanctuary, the security is Your security, and this is the station of one seeking refuge in You from the Fire. O Allah, You called to the Hajj of Your Sacred House and we came, listening and obeying, so forgive us and have mercy on us as You commanded us. O Allah, accept from us, raise our ranks, and join us with the righteous.",
      source: "المأثور",
      categoryName: "الأدعية الطويلة الكاملة",
      mansakKey: "tawaf_wada",
      isFeatured: false,
      duaType: "long",
      orderIndex: 1,
    },
    {
      titleAr: "دعاء الحاج الجامع الكامل",
      titleEn: "Comprehensive Hajj Dua",
      arabicText: "اللَّهُمَّ اجْعَلْ حَجِّي مَبْرُورًا وَسَعْيِي مَشْكُورًا وَذَنْبِي مَغْفُورًا وَعَمَلِي مَقْبُولًا، اللَّهُمَّ تَقَبَّلْ مِنِّي كَمَا تَقَبَّلْتَ مِنْ إِبْرَاهِيمَ خَلِيلِكَ وَمُوسَى كَلِيمِكَ وَمُحَمَّدٍ حَبِيبِكَ صلى الله عليه وسلم، اللَّهُمَّ ارْحَمْنِي بِرَحْمَتِكَ الَّتِي وَسِعَتْ كُلَّ شَيْءٍ، وَلاَ تُعَذِّبْنِي وَأَنَا أَدْعُوكَ وَأَرْجُوكَ",
      translationAr: "اللهم اجعل حجي مبروراً وسعيي مشكوراً وذنبي مغفوراً وعملي مقبولاً. اللهم تقبل مني كما تقبلت من إبراهيم خليلك وموسى كليمك ومحمد حبيبك صلى الله عليه وسلم. اللهم ارحمني برحمتك التي وسعت كل شيء، ولا تعذبني وأنا أدعوك وأرجوك",
      translationEn: "O Allah, make my Hajj accepted, my Sa'i thanked, my sin forgiven, and my deeds accepted. O Allah, accept from me as You accepted from Ibrahim Your close friend, Musa Your interlocutor, and Muhammad Your beloved ﷺ. O Allah, have mercy on me with Your mercy that encompasses all things, and do not punish me while I am calling upon You and hoping in You.",
      source: "المأثور",
      categoryName: "الأدعية الطويلة الكاملة",
      isFeatured: true,
      duaType: "long",
      orderIndex: 2,
    },
  ];

  let inserted = 0;
  let skipped = 0;

  for (const dua of duas) {
    const catId = catMap[dua.categoryName];
    if (!catId) {
      console.warn(`Category not found: ${dua.categoryName}`);
      continue;
    }

    const existing = await db
      .select({ id: duasTable.id })
      .from(duasTable)
      .where(eq(duasTable.titleAr, dua.titleAr))
      .limit(1);

    if (existing.length > 0) {
      skipped++;
      continue;
    }

    const { categoryName, ...duaData } = dua;
    await db.insert(duasTable).values({
      ...duaData,
      categoryId: catId,
    });
    inserted++;
  }

  console.log(`Done! Inserted ${inserted} duas, skipped ${skipped} existing.`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
